### ISSUE TITLE
[Enhancement]: Configurable bitrate for m4b-merge

### ISSUE THREAD

**Issue by heikomat** [advplyr/audiobookshelf#1029]
### Describe the feature/enhancement

I'd love to have a little control over the quality of the files generated via the awesome m4b merge feature.

I usually use Apple music to convert my Audiobook-CDs to M4A-Files using its AAC-encoder. As i understand it, m4b also uses AAC, so i guess their bitrate-to-quality-ratios are probably comparable? If so, the default 64 kbps used in audiobookshelf might be a little low for some scenarios.

I do understand that for most cases it's probably fine (and even desirable considering space- and bandwitdh-savings). But i do really like hearing the incredible detail (especially in the highs) that some recordings have when listened to on a somewhat nice pair of headphones.

Because space and bandwidth are not an issue for me, I usually set my AAC-encoding-bitrate to (maybe a tad overkill? maybe not?) 192 kbps and would love to be able to do the same in audiobookshelf.

**Comment by andrewls** [comment]
Another alternative to this would be to set the target bitrate based on the codec and bitrate of the source files. Encoding at 192kbps AAC makes no sense if your source file is a 64kbps mp3

**Comment by mobywan85** [comment]
Where in the codebase is the bitrate set? I would love to be able to manually just change it?

**Comment by advplyr** [comment]
I haven't dug into this yet but I think @andrewls has the right approach in using the bitrate of the source file.

Abs also supports merging multiple m4b's using this tool and for that it should already be maintaining the bitrate since no encoding is required.

Here it is in the codebase where the options are set for ffmpeg. 64k is hardcoded at the moment and as a temp solution can be increased for the next release.

https://github.com/advplyr/audiobookshelf/blob/master/server/managers/AbMergeManager.js#L107

As it is now Abs is already attempting to get the bitrate from audio files when they are scanned. Most likely this is not going to be the case in the future because we are switching to Tone library which will only be extracting meta tags. For that reason we should have the merge tool first do an ffprobe on one of the mp3s to get the source bitrate.

**Comment by advplyr** [comment]
I'm wondering what ffmpeg will output if we set the default bitrate higher then the source bitrate.

**Comment by Alcedema** [comment]
I also came on here to ask for customisable nitrate, but yes, ffprobe on encode start to set a bit rate comparable to the source would be best! Thanks!

**Comment by advplyr** [comment]
Added in [v2.2.11](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.11)

This is just a quick and dirty implementation so you can adjust these settings. Will leave further updates to encoding options for https://github.com/advplyr/audiobookshelf/issues/1257

![image](https://user-images.githubusercontent.com/67830747/208550727-2b4712c6-40cd-490d-b568-4c24e2f17e67.png)
