### ISSUE TITLE
[Bug]: ID3 tags not recognized

### ISSUE THREAD

**Issue by Brancliff** [advplyr/audiobookshelf#1040]
### Describe the issue

New to Audiobookshelf, and I saw the ID3 tags described in the documentation. I whipped up a test audio file to make sure that everything was working.

![image](https://user-images.githubusercontent.com/22332774/193722271-a2e1f4f2-8d35-48f4-b97e-ee0d1728aeaf.png)

However, once I added it to my Audiobookshelf/Podcasts folder, the file came out with none of its metadata. It is titled "test", but it may have just taken that from the filename.

![image](https://user-images.githubusercontent.com/22332774/193722427-32cc78a4-bb58-46bb-b2ee-e26d9682e8a9.png)

"Prefer audio metadata" is enabled in the settings.

### Steps to reproduce the issue

I just wrote the test file and then made an "example podcast" folder in the podcast directory to use. I also tried a force rescan to see if that would help (it didn't).

The crazy thing is, I tried the Tone CLI since the new version is using that, and that was able to detect the metadata.

![image](https://user-images.githubusercontent.com/22332774/193722919-20430584-3a6a-4bc4-ab51-cecc5348d350.png)

I could maybe send over the test file if that might help?

### Audiobookshelf version

v2.2.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Those meta tags listed in the docs are for book libraries only. Currently podcasts aren't using any meta tags but we plan on implementing that. A discussion was opened up yesterday about this #1038

Tone isn't being used to read meta tags yet either since I'm waiting on the next release that will let us handle errors. I'm going to wait on implementing the podcast meta tags until Tone is swapped in as the primary meta tag reader. Tone is used to write meta tags though.

Since this isn't a bug I'm going to close this. We can discuss this feature in #1038
