### ISSUE TITLE
[Bug]: No automatic match with Audible because of wrong search string

### ISSUE THREAD

**Issue by PlzSpamMeNot** [advplyr/audiobookshelf#1042]
### Describe the issue

The books are not automatically matched with Audible because the search text is generated incorrectly.

In the field "Search Title or ASIN", the author is automatically written before the book title. This means that you won't find anything on Audible.

If you delete the author manually, Audible will find the book.
(remark: my books are in German)

![image](https://user-images.githubusercontent.com/114874715/193802068-00036111-60dc-44ab-a80b-6bc947af703c.png)

Off-topic - possible feature request: Since there are sometimes books in two versions - a normal version and an abridged version - it would make sense to take the duration of the book into account or display it in the matching UI.

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.2.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I don't believe this is a bug because the search title is just getting prefilled in to whatever the title is set in the Details tab. The title set in the details tab is coming from either your folder structure OR meta tags embedded in your audio files.
My guess is that you have named your book folder in that way with author name first.

Refer to the docs https://www.audiobookshelf.org/docs#book-title-folder on folder structure & naming.
