### ISSUE TITLE
[Enhancement]: shared state between users

### ISSUE THREAD

**Issue by rhyst** [advplyr/audiobookshelf#1045]
### Describe the feature/enhancement

There are some podcasts that I listen to alone and some that I listen to only with another person. Something I would really like but as far as I know no podcast app supports is the ability to share podcast state between two people so that the "continue listening" and "finished" states are shared between the accounts.

I can think of two ways this could work for me:
- Flag a podcast as being shared - all state is shared between accounts whenever either account listens to that podcast
- Some way to state who you are listening with when starting a podcast, then all state is shared for any podcast that is played

Is this the sort of thing you would accept a PR for?

**Comment by advplyr** [comment]
I don't understand the use-case for this, why would you want to share listening state?

This would a bigger project as it would require either changing the data model of media progress objects or keeping copies of the same media progress object in each user.

**Comment by advplyr** [comment]
I think it would be a big project for an uncommon use-case. It wouldn't be as simple as copying the media progress. We also have syncing of progress as well as android auto (and iOS car play eventually) that don't have an interface we can ask the user to select which progress to use. Then we have completely offline listening which keeps progress locally and syncs it when the server is connected. The mobile app repo is https://github.com/advplyr/audiobookshelf-app

If you have a solution that could fit in the existing data model then I'm open to it but just thinking about this for the last few minutes has me overwhelmed!

**Comment by ponchohoncho** [comment]
For what it's worth, I came here to request this same thing. I have the same use case: I listen to a book with a partner and it's always a toss up who's phone is closest, on, or otherwise available. We also listen to our own books, and sometimes the same book but at different rates, so sharing a single account won't work here.

As far as UI and permissions & such go, this is how I could imagine it would go. There's two parts: permission to sync/share state, and the state sharing itself.

There would need to be some kind of very light friend system, where you could consent to sharing your media progress with another specific user, For ease of use, we make it bidirectional in nature, like FB friends, rather than unidirectional like Twitter follows. It could be as granular as "I want to share the media progress of this book with this user" and then that user gets a notification to accept that connection. Then the consent/permission is there for future media progress syncing.

The syncing UX could be implemented only on the app side, don't worry about car interfaces, they're just for playback. You don't expose dual book/chapter seek bars to the car interface, so don't worry about this one either.

In the 3 dots menu on the playback screen, there'd be a new item called "Catch up with your friend's progress" or something similar. Tap that and you get a confirmation that you'd be moving your progress to Chapter Y at time HH;MM;SS, which was last played by your friend Z days ago on MM/DD/YY, and to confirm or cancel. Bonus to give a warning that your current playback position is later, or more recent than your friends and are you sure you want to go backwards? The date of last sync would let the people doing the sync say "yeah, that was the other day when we got groceries" or "wait, that's too long ago, remember, we were offline last week, let me open my app and sync my media progress up".

I think that accounting for offline listening is a red herring, and not worth a ton of thought. Let the user know that it's a best effort kind of thing and that obviously, the app can't know things that it doesn't know (such as where an offline user is in their book).

**Comment by bjhiltbrand** [comment]
I just came here to request the same enhancement for the same reasons. I think @ponchohoncho has a pretty straightforward idea for how to make this work.

**Comment by zerodogg** [comment]
For me, I'd be happy with just being able to view another persons location in a podcast/audiobook. As state syncing fits poorly into the data model as @advplyr said, being able to view another persons progress and just manually jumping to it would, at least for me, be a perfectly viable solution for what is probably a somewhat niche feature.

**Comment by w4itey** [comment]
This Feature would also be good for me and my wife, and zerodogg's answer would also work just find, just a way to get my book in sync with their book.

**Comment by Jab2870** [comment]
Just wanted to weigh in and say that this would be extreamely useful for me. THere are a couple of podcasts I listen to with my wife and sometime on my device, sometimes on hers.
