### ISSUE TITLE
track calculation is wrong

### ISSUE THREAD

**Issue by mprivoro** [advplyr/audiobookshelf#108]
(mp3 files) track number calculation looks wrong or not working.

mp3 track that shown by ffprob for example is like this

```
Input #0, mp3, from 'Azazel-02.mp3':
  Metadata:
    album           : Azazel
    artist          : Boris Akunin
    album_artist    : Boris Akunin
    genre           : Audiobook
    title           : Azazel-02
    track           : 02
    date            : 1998
  Duration: 00:11:30.16, start: 0.025057, bitrate: 192 kb/s
    Stream #0:0: Audio: mp3, 44100 Hz, stereo, fltp, 192 kb/s
    Metadata:
      encoder         : LAME3.92 
```

but server crawler detects it like 1 and prints "Duplicate track number"

Described above is happening for 20% of my collection

**Comment by mprivoro** [comment]
I debuged a little bit audioFileScanner.js
looks like gathering the track number is OK, so might be wrong in DB update or any other internal procedure?

![image](https://user-images.githubusercontent.com/7849370/137580396-ae74dbbf-53a0-4312-8b56-8290c5345933.png)

**Comment by mprivoro** [comment]
also it looks like clicking this button is not taking the all files into account

![image](https://user-images.githubusercontent.com/7849370/137590013-976afd70-30a3-4e5d-a1b2-7a8ca912371f.png)

**Comment by advplyr** [comment]
Yeah it is only looking at audio tracks, which would exclude audio files with errors or that you intentionally excluded.

Given those 2 results it looks like the scanner is working fine for your files.
When you added those audiobooks did you already have them in the directory when you pressed scan? Or did you move them into the directory after?
Have you moved any audio files in either of those 2 examples you shared?

The reason I ask is because there are only 2 times where the track number gets set. The first scan and when new audio files are added.

**Comment by mprivoro** [comment]
Yah, something like that.
I saw that some track are not OK, so i went to the files and fixed them manually - tried to reindex to fix the issue...
now i see that once i'm removing the book from the system and then reindexing - everything is OK.

so it more looks like my misunderstanding the system's flows rather than bug.

i **very** appreciate your help and want to thank you on creating such system!

thank you!
