### ISSUE TITLE
[Bug]: ABS not marking dl'ed episodes from feed as dl'ed

### ISSUE THREAD

**Issue by louisjg** [advplyr/audiobookshelf#1108]
### Describe the issue

This ticket came from an enhancement request where I asked for duplicate detection.  abs shouldn't create duplicates, so I went and repro'ed the issue where dl'ed episodes are not being marked as present.

NOTE:  This is the same podcast that drops the 4th episode because maxdownload was hardcoded to 3, so may be related.

I look at my episode list and see a bunch of episodes are there.  They actually exist and play. (C2Cepisodelist.png)
![C2Cepisodelist](https://user-images.githubusercontent.com/42064378/199352820-419f44d3-2501-428d-b55a-feb59a626f8e.png)

Going to the searchlist for the feed, only the last few downloaded are checked (C2Csearchlist.png)
![C2Csearchlist](https://user-images.githubusercontent.com/42064378/199352825-3326decc-f640-4e1b-b5bb-178a9eab596e.png)

Looking at one of the episodes that is not checked, it does in fact have an RSS URL assigned to it (C2CEpisodeURL.png)
![C2CEpisodeURL](https://user-images.githubusercontent.com/42064378/199352824-dfac2c28-b155-46c6-984b-6f1108f86807.png)

I didn't see anything interesting in the log, but I can capture logs and add log output to the code upon request.

### Steps to reproduce the issue

Unknown trigger.  Reproduces itself

### Audiobookshelf version

v 2.2.1

### How are you running audiobookshelf?

Docker

**Comment by louisjg** [comment]
Oh, I just realized I don't have "Enable automatic library scans" enabled for that library.  I don't have problems with other podcasts in the library, so not sure that's relevant.  All my current podcasts are downloaded by RSS feed rather than imported in for that same library.

**Comment by advplyr** [comment]
The way Abs is determining whether or not the episode was downloaded is by comparing episode url (in your last screenshot) with the episode url coming from the RSS feed.
My guess is that the RSS feed is changing that URL. You can open the RSS feed in your browser and find the episode URL for an episode and compare it with the one in Abs.

Since this is a private podcast feed I have no way to test this for myself.

Library scans have nothing to do with this so don't worry about that. The only part that matters is that URL in the final screenshot.

**Comment by louisjg** [comment]
OK, I will take a look and compare and post my findings.  Thanks!
