### ISSUE TITLE
Enhancement: Keyboard control (Play/Pause with spacebar, etc.)

### ISSUE THREAD

**Issue by juriroemer** [advplyr/audiobookshelf#121]
Would love to be able to control AudioBookshelf via the usual keyboard inputs - some suggestions:

- space: play/pause
- arrow left/right: jump 10 seconds
- arrow up/down: raise/lower volume
- l: open/close playlist view
- escape: close player
- (m: mute/unmute)

**Comment by advplyr** [comment]
I just added some of these in `v1.4.14`, but put it in experimental features because I haven't tested it enough yet.

If you have experimental features on it should work like this:

[Space] : Play/Pause
[ArrowLeft] : Jump backward 10s
[ArrowRight] : Jump forward 10s
[ArrowUp] : Increase volume 10%
[ArrowDown] : Decrease volume 10%
[M] : Mute/Unmute

If you have an input field focused OR any dialog is open it will ignore the hotkeys.

I just realized as I'm writing this that I forgot to check if the e-reader is open, so they will still work if the e-reader is open but I will fix that tomorrow.

I plan on mapping the escape key to close the player or any open dialogs, which is a bit more involved so I held off on that one for now.

I'm not sure what you meant by the playlist view.

**Comment by juriroemer** [comment]
Wow, that was fast, exciting!
Mapping the escape key like that sound great. Mapping something like [Shift] + [Up/Down] to increase/decrease playback speed would also be nice.
Just had a super quick look at the code, what I meant to trigger/toggle with [L] is the showChapters() function.

**Comment by advplyr** [comment]
I added these hotkeys and included in release [v1.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v1.5.0)

This is no longer experimental. I will need to put these somewhere people can find.
