### ISSUE TITLE
[Enhancement]: OPML Export

### ISSUE THREAD

**Issue by Dragonatorul** [advplyr/audiobookshelf#1260]
### Describe the feature/enhancement

It would be nice to be able to export an OPML file of all the current podcasts. It would help with issues like needing to re-create the podcast library or with keeping a separate backup of podcast subscriptions, such as in a separate podcast application.

**Comment by lerra** [comment]
It would be great to get OPML export, pref via a URL so it would be easy to add to mopidy with the podcast extension

**Comment by advplyr** [comment]
This is on the library page for podcast libraries in the context menu. It will only be visible to users with download permission.

I set it up so that it opens in a new tab instead of downloads so you can use the link directly if you need to. It is protected with an API token though.

Also note that the podcast must have an RSS feed for it to show up in the OPML.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/03b415d7-367e-4ec4-b3ca-889a7bd6b367)

I couldn't think of a better place to put this. Let me know if you have suggestions.

**Comment by advplyr** [comment]
Added in [v2.2.22](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.22)
