### ISSUE TITLE
[Enhancement]: Could you add instructions for NginX Proxy Manager?

### ISSUE THREAD

**Issue by LostOnTheLine** [advplyr/audiobookshelf#1307]
### Describe the feature/enhancement

It's very simple, but the NginX instructions don't really work when using `NginX Proxy Manager`

- `Scheme` must be set to `http` (even thought _**externally**_ it will be `https`)
- `Websocket Support` must be `Enabled` (This is listed at the top of the Reverse Proxy section, but a reminder in the instructions doesn't hurt since you have to remember to flip it's switch)
- I `Block Common Exploits` of course, but that isn't required, just recommended & from my limited experience does not cause any problems
- Under `SSL` set it up however you normally do & make sure to enable `force SSL` otherwise the whole thing is meaningless as it could be access without SSL by simply typing `http` instead of `https`
- Make sure to agree to `Let's Encrypt Terms of service`
- No `Advanced` Settings needed at all, no code to copy, nothing
- It seems to support `HTTP/2` even though the internal direct page does not, so support can be enabled, but I'm not too familiar with it so I don't know the particulars so I cannot say it will work without issue or that it will actually do anything. I just know it's more efficient & some things don't work with it enabled
- `HSTS Enabled` also seems to work, I'm not an expert on that either, I personally just turn it on unless it being on causes a problem. But you should have a better idea if the app would have any problems with those & could advise to not use it if so or just say **_"Users have reported no issues with `HTTP/2` or `HSTS` so far, but use these claims have not been verified, use at your own discretion"_** or something like that

**Comment by advplyr** [comment]
There is already instructions for Nginx Proxy Manager here
https://github.com/advplyr/audiobookshelf#nginx-proxy-manager

It is only one screenshot because the default NPM config works with Abs with the only step being you need to enable Websockets Support.

What you are describing is also setting up an SSL certificate which would be out of the scope of our documentation. However, users have started contributing guides on doing various things in Abs and this could fit well in there. The guides aren't linked anywhere yet but they live here https://www.audiobookshelf.org/guides

The guides are just markdown files here https://github.com/advplyr/audiobookshelf-web/tree/master/content
so feel free to contribute a guide!

**Comment by fogolin** [comment]
I was just looking for it, created a PR with this guide here:
https://github.com/audiobookshelf/audiobookshelf-web/pull/82
