### ISSUE TITLE
[Enhancement]: Bookseries metadata

### ISSUE THREAD

**Issue by ScuttleSE** [advplyr/audiobookshelf#1311]
### Describe the feature/enhancement

When opening a book series, I would like to have space to enter metadata about the series and which books goes into that series. Would give one an opportunity to keep track of books one might be missing in a series.

**Comment by advplyr** [comment]
Can you give an example of what you think this should look like? I don't think I'm understanding

**Comment by ScuttleSE** [comment]
Something like what audible does. https://www.audible.com/series/Xeelee-Sequence-Audiobooks/B07F93R4DW

There you can see that books that aren't available are still listed, and there is a short blurb about the series

**Comment by advplyr** [comment]
There is already a request open for showing missing books in series #963
I'm not sure yet if this will ever be added since we need a reliable source to retrieve this info.
If you're referring to adding the missing book information in manually then this isn't something that will be supported at this time.
