### ISSUE TITLE
[Enhancement]: parental control

### ISSUE THREAD

**Issue by puregreen59** [advplyr/audiobookshelf#1316]
### Describe the feature/enhancement

So my kids are just starting to get to the age where they want there own access to audio books.

but i don't want them to be able to listen to anything i didn't approve,

I've had a good poke around and didn't find a way of doing this other than making a copy the same audio books and setting up another library and doing it that way.

i thought about doing tags but that didn't work as they audio book wasn't in there empty library folder.

would be great to have a simple right click and  "share with *USERNAME*" or "Approve access with *USERNAME*"

**Comment by advplyr** [comment]
The "share with username" approach doesn't work as well with the data model of Abs like it does with Plex. We could figure out a way and implement that in the future but maybe there is another approach that could work for you.

I'm not understanding why the tags didn't work?

**Comment by puregreen59** [comment]
That's fair enough,

As for tags I made a separate library, called it kids, pointed it to a empty folder, then I tagged a appropriate audiobook from my normal library and added that tag to my kids account but it didn't show up.

Was that the correct method? I mean honestly if I can get that to work, then that would do the trick nicely to be honest!

**Comment by hobesman** [comment]
With tags, the kids would have to be in the same library, and if you enable it, they'll only have access to the books with those specific tags.

What I was hoping this request would be about was time limitations, either amount of time, or time windows, or both. I realize that would be hard to enforce with downloaded books, but I already disabled downloading for my kids' accounts so I could control their use by cutting off their wifi access after bedtime (they don't have mobile data). They would stay up all night listening if I didn't cut them off. Or if I want them to do their chores before they get more time. But it would be nice to control that within abs too/instead, since sometimes I want things like location services and WiFi calling to still work. Also, they could just pick up another device (like a sibling's phone) and continue listening since it's device based and not a per-account block.

Should I open a separate request for that kind of time management?

**Comment by advplyr** [comment]
@puregreen59 It seems you misunderstood what the tag restriction is as @hobesman pointed out.

@hobesman Have you seen this sort of thing in other software? Seems like a huge feature to build out but I may not be understanding.
