### ISSUE TITLE
[Enhancement]: One -> Many Genera/Tag renaming

### ISSUE THREAD

**Issue by cassieesposito** [advplyr/audiobookshelf#1347]
### Describe the feature/enhancement

In the Item Metadata Utils interface, it would be nice to be able to convert a single tag in to two tags. The use case is that many books get "genera" from the scrapers like "Juvenile Fantasy," and the most useful thing to do with this is to give every one of those library items both the "Juvenile" genera and the "Fantasy" genera so that it will appear when either one is filtered for.

**Comment by advplyr** [comment]
I think it would be better to use the batch editor for this. You can filter for that genre, then select them all and batch edit.

The batch editor now allows for appending Genres/tags/etc.

![image](https://user-images.githubusercontent.com/67830747/210176147-2fdfe96e-3c91-4314-881f-3b2c22fc6411.png)

Otherwise we need some UI/UX designed for "Split into 2 genres" with 2 text inputs.
