### ISSUE TITLE
[Bug]: When adding podcasts using OPML it will append backslash (\) to the path rather than forward slash causing directory issues on *nix

### ISSUE THREAD

**Issue by dmurphy22** [advplyr/audiobookshelf#1384]
### Describe the issue

When adding podcasts using OPML import it will create directories for those podcasts using a backslash in the directory string. This is a problem on *nix as it does not create the correct directory structure.

Image shown directories are being created one directory above the intended one with `podcasts\` appended to the folder name. 
![Screenshot 2023-01-09 193611](https://user-images.githubusercontent.com/6827863/211456418-97cae4d5-7e7c-4f57-9265-4b7130161da0.png)

image showing modal with backslash in directory. 
![Screenshot 2023-01-09 193736](https://user-images.githubusercontent.com/6827863/211456530-6e64093f-28ca-44a8-a105-d3ac001efd68.png)

### Steps to reproduce the issue

1. Import OPML podcasts
2. Notice in modal that directories include backslashes
3. View errant directories after import

### Audiobookshelf version

v2.2.12

### How are you running audiobookshelf?

Docker

**Comment by Brandelan** [comment]
Had this issue as well with the same setup on my Synology NAS. Seems like it was downloading the files local to the docker image, and were inaccessible to me.

**Comment by RichyHBM** [comment]
Can confirm I am seeing this also using the docker image on a ubuntu host (though I imagine this happend based on the docker image being linux based regardless of the host)

From what I can see the issue seems to come from https://github.com/advplyr/audiobookshelf/blob/946e4f39cc9a8ada7d467e8bca8751330b7588ba/client/components/modals/podcast/OpmlFeedsModal.vue#L127 being hardcoded to use windows style separator, ideally this should be set by the server using something like https://nodejs.org/api/path.html#pathsep, I'm not too versed with nextjs to confidently submit a PR but maybe this info can help?

As it stands OPML import doesnt seem to work on any linux platform hosting AudioBookShelf, this includes the docker image

**Comment by advplyr** [comment]
I didn't see this issue earlier and created a dupe #1476

This is fixed for the next release already so we'll keep #1476 as the main thread.
