### ISSUE TITLE
[Enhancement] Embed metadata in audio files & scan OPF file metadata

### ISSUE THREAD

**Issue by rubbo898** [advplyr/audiobookshelf#141]
I'm using Calibre to fetch metadata from online datasources (Amazon and Google in the first place).
For it's internal logic it creates .opf files for backup/restore purposes, it would be great having the feature to embed these metadata  into audio files (eg mp3tag) from .opf files. 

With a wider perspective: embed metadata from an external datasource (online? file?) into the audio files

**Comment by advplyr** [comment]
I just pushed `v1.6.13` that looks for a `metadata.opf` or `metadata.xml` file and extracts the following:

```
title, author, narrator, publishYear, publisher, isbn
```

I skipped description for now because calibre stores description as HTML and audiobookshelf uses plain text only. It may make sense for audiobookshelf to support HTML in the future.

The current order of precedence for setting metadata is
1. Folder & filenames
2. desc.txt & reader.txt
3. metadata.opf & metadata.xml
4. Audio file ID3 tags

This order is not adjustable yet.

**Comment by rubbo898** [comment]
What a great news! It looks for a metadata.opf file with the same name of the audio file? Or is mandatory that the .opf is named "metadata"? 

I've performed some test and it seems that the .opf file isn't recognized:

 
![InkedImmagine 2021-11-09 095444_LI](https://user-images.githubusercontent.com/55589568/140894446-da00be26-d1f4-4296-8157-6adb0d44998f.jpg)
![InkedImmagine 2021-11-09 095511_LI](https://user-images.githubusercontent.com/55589568/140894451-250e2ec5-c93d-4572-be1d-94f8abc3cc9b.jpg)

Here below the .opf file:

[Il sangue della lupa.zip](https://github.com/advplyr/audiobookshelf/files/7503387/Il.sangue.della.lupa.zip)

OT: I'm trying to set up Treafik as reverse proxy, it works via web UI but not with the App.

**Comment by advplyr** [comment]
Thanks for sharing your opf file, I was able to extract more information after seeing your example.

I updated the scanner to find any file with the extension `.opf`, instead of just `metadata.opf`.

I noticed that the description in the one you shared was plain text and not html, so I added a check to see if the description is plain text and if it is it will use it.
I added genres too, so the genres in your example will populate.

The new full list of metadata extracted is:
```
title, author, narrator, publishYear, publisher, isbn, description, genres, language
```

To test it I removed all the details of a book in my library, put your opf file in the directory, then pressed re-scan.
![image](https://user-images.githubusercontent.com/67830747/141040080-2cb96645-2b49-4771-a518-c42e8a40422f.png)

This is `v1.6.14`

**Comment by jarrodCoombes** [comment]
Would it be possible to add an option to save the meta data out to a file in the folder with the MP3s, similar to what happens with cover images?

**Comment by advplyr** [comment]
That's what the "Save Metadata" button is supposed to do. Although it is probably not complete since it was before a lot of the details were added.
Is that not working for you?

**Comment by jarrodCoombes** [comment]
Ahh, ok. I honestly had no idea what that button did, and completely missed the tool tip when you hover it. I'll test it and let you know, but I suspect it probably works fine.

**Comment by rubbo898** [comment]
It's working as described, awsome!

Where can I find the language tag? I didn't spot it in any menu.
Embed metadata in the ID3 is the last piece but I understand is a critical step, thanks a lot for your efforts!

**Comment by advplyr** [comment]
I haven't exposed the language field yet. I added it because I anticipate this will be requested at some point. I try not to clutter up the UI with stuff people won't use.

**Comment by jarrodCoombes** [comment]
> I haven't exposed the language field yet. I added it because I anticipate this will be requested at some point. I try not to clutter up the UI with stuff people won't use.

This would suggest the need for the option in the "Settings" page where people can turn this on and off.

**Comment by rubbo898** [comment]
> I haven't exposed the language field yet. I added it because I anticipate this will be requested at some point. I try not to clutter up the UI with stuff people won't use.

Got the point!

2 secondary question:

1. Is there any way to perform bulk actions like scan & grab metadata from .opf files and save metadata on the whole library or a portion of it? Select all + modify is missing this feature right now, are you planning to add it in the future? 
2. "Save metadata" now create a "metadata.nfo" file, from a library perspective do you think a metadata file named like the audio file could be more "accurate"?

**Comment by advplyr** [comment]
There is still no option for batch saving metadata, I think there is another issue open for this. I'm doing some house cleaning now because I lost track of a lot of threads it seems.
I'm not sure about the naming of the metadata file, it seems common practice to use the same name in each folder.

**Comment by wtanksleyjr** [comment]
> When scanning, if an .opf file is present it will be parsed and mapped to audiobookshelf fields.

Can someone who's gotten this working please post an example, ideally using all of the supported fields? There doesn't seem to be any document that defines this format in the terms used in this discussion (the fields of that format don't include an "author", for example, but rather a "contributor" with a subfield something like "aut" IIRC). It's incredibly complicated so far as I can tell.

Is it possible to set a book's series using this OPF file? I can't tell how to do that at all, but some of my books appear in series for reasons I ... can't tell at all. Some of them appear in a series named as the author, I'm guessing because I'm following the wrong naming conventions.

**Comment by advplyr** [comment]
There is no documentation written for the specifics of how OPF files are mapped to abs details. Here is the relevant code for the parsing: https://github.com/advplyr/audiobookshelf/blob/master/server/utils/parseOpfMetadata.js#L73.
I linked to the line that will pull the series from the OPF file, using tag `calibre:series`

The incorrect series getting filled out for you is most likely due to your folder structure. See https://www.audiobookshelf.org/docs#structure
You can use the folder structures:
<Author>/<Series>/<Title>/
<Author>/<Title>/
<Title>/

**Comment by wtanksleyjr** [comment]
Thank you for both pointers! That doesn't look too hard to figure out. And
of course I see what my directory structure got wrong.

-Wm

**Comment by advplyr** [comment]
This was added a while back and just getting refined now
