### ISSUE TITLE
[Bug]: Name verification fails when creating a library

### ISSUE THREAD

**Issue by lkiesow** [advplyr/audiobookshelf#1427]
### Describe the issue

When creating a new library, the name verification (and therefor the library creation) fails if you type the library name right before clicking create.

### Steps to reproduce the issue

- Open “Add Library” dialog
- Add a folder
- Click in the “name” input and type a name
  - Do not leave the input
- Click “Create”
- You will get the error “Library must have a name”

It seems like the name is stored only after the event that is trying to create the library

- Click “Create” again
- Now it works

### Audiobookshelf version

v2.2.12

### How are you running audiobookshelf?

Debian/PPA

**Comment by advplyr** [comment]
The input field has to get blurred that's why. The button component uses preventDefault for other reasons which then requires manually blurring inputs.
Here is an example of blurring input before submitting. https://github.com/advplyr/audiobookshelf/blob/master/client/components/widgets/BookDetailsEdit.vue#L171

**Comment by advplyr** [comment]
Fixed in [v2.2.13](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.13)
