### ISSUE TITLE
[Enhancement]: Paginate APIs for low resource devices 

### ISSUE THREAD

**Issue by gordallott** [advplyr/audiobookshelf#1504]
### Describe the feature/enhancement

in memen45/SubMusic/issues/67 We've been discussing adding audiobookshelf backend support to a Garmin wearable app used to sync & play audiofiles from hosted servers (plex, nextcloud, ampache...) so you can listen to things directly from the watch and keep things in sync 

One of the bigger points of contention with adding support is the lack of pagination in audiobookshelf APIs, hitting an api like `/api/items/$libraryID?expanded=1&include=authors,downloads,rssfeed` can easily hit a few MB in json for podcasts especially. For reference I have a podcast with 500~ items that produces about 2MB of json 

adding pagination to the Libraries/Playlists/Collections apis would go a long way towards both making it possible to interact with the server on low resource devices, as well as making the general user experience better, especially for podcast users

**Comment by advplyr** [comment]
Library items, playlists, collections, and series all have pagination.

See the docs https://api.audiobookshelf.org/#get-a-library-39-s-items

They are in the Library section because they are library dependent for clients. You can also pass `minified=1` to get a smaller object for library items.

Let me know if there is anything else.
