### ISSUE TITLE
[Bug]: Unrecognised characters in Firefox

### ISSUE THREAD

**Issue by shepda** [advplyr/audiobookshelf#1508]
### Describe the issue

There are unrecognised characters after each of the play speed options in Firefox. Tested in Brave and these are not appearing so it doesn't appear to be an issue in Chromium browsers.

This issue is when using Firefox on Linux, I've not tested to see if the same issue is present in Firefox on Windows or MacOS.

Firefox version 109.0.1 on Linux
Audiobookshelf version 2.2.15 on Docker

Screenshot from Firefox
![Screenshot from 2023-02-15 11-46-15](https://user-images.githubusercontent.com/6839214/219020442-f8fe8d6a-f904-4d5f-a562-94040c6dd739.png)

Screenshot from Brave
![Screenshot from 2023-02-15 11-53-08](https://user-images.githubusercontent.com/6839214/219020496-68d0e816-1fa0-48a7-9dea-641a188c4bd5.png)

### Steps to reproduce the issue

1. Play a podcast using Firefox on Linux
2. Note the unrecognised characters after the play speed options

### Audiobookshelf version

2.2.15

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Just tested this in Firefox on Windows and it is not an issue there.

This is what it looks like on Brave & Firefox for Windows.

![image](https://user-images.githubusercontent.com/67830747/219514484-c55a182f-88f1-4f96-a924-c659ed85742a.png)

I went ahead and replaced that unicode character with a regular x since it was unnecessary

New:
![image](https://user-images.githubusercontent.com/67830747/219515234-8a5769a6-6709-4a56-81c5-e4a91e4c6c4a.png)

**Comment by shepda** [comment]
That's great, thanks!

**Comment by advplyr** [comment]
Fixed in [v2.2.16](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.16)
