### ISSUE TITLE
[Bug]: Remaining time -NaN

### ISSUE THREAD

**Issue by J4gQBqqR** [advplyr/audiobookshelf#1509]
### Describe the issue

I have a book that shows NaN remaining time.
![Screenshot_20230215-202325-901](https://user-images.githubusercontent.com/77554817/219237661-9bc79ac1-0caa-4cc1-81d8-ba8aadd32da5.png)

### Steps to reproduce the issue

I can provide you the file if you need it for debugging. 

### Audiobookshelf version

v2.2.15

### How are you running audiobookshelf?

Docker

**Comment by J4gQBqqR** [comment]
Well, I kept playing and the time appears after episode 7. Then I went back to the episode that is problematic and unable to repeat the behavior.

**Comment by hobesman** [comment]
Just FYI, this is related to the playback speed being reset incorrectly by the app. You'll see in your screenshot the playback speed just says "x" instead of "1x" or whatever. Once the speed gets set properly, it calculates the remaining time.

It's a known bug though so you can leave this issue closed for now.
