### ISSUE TITLE
[Enhancement]: Find author image if the current file does not exist on the drive

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf#1607]
### Describe the feature/enhancement

So, I restored my backup from a Linux machine to a windows docker, but was unsuccessful as the paths to my books were different. However, as I only cared about my statistics, which I got restored during my back up, I deleted the current library and just added the new path as a new library. In the process of restoring though, the authors were added and all have an image file path stored with them, which do not exist on this server. And on matching authors, it does not fetch new image since it thinks the image path is there so the image must also be there, which is not the case.

I can remove the image path and rematch and it works, but doing a few hundreds of them seems tedious, hence this feature request.

I did a find and replace using regex in the authors json files, but that wont be possible for any normal user.

This will probably be one of the least important edge cases to cover but I thought I'd put it here just for the record.

**Comment by nichwall** [comment]
Is this still an issue in 2.16.2? This issue was opened prior to the migration to SQLite in July 2023, so I assume it is now resolved since the author json files no longer exist.

There have been some fixes to backup restore behavior including https://github.com/advplyr/audiobookshelf/issues/2904 to fix author images not being restored, and resetting the image cache after restoring from backup to force the cache to be rebuild https://github.com/advplyr/audiobookshelf/issues/3272.

**Comment by advplyr** [comment]
Yeah looks like this would be fixed with #2904 but we can re-open if not
