### ISSUE TITLE
[Bug]: Timestamps in chapter list do not respect playback speed shift

### ISSUE THREAD

**Issue by KF5JWC** [advplyr/audiobookshelf#1647]
### Steps to reproduce the issue

1. Change playback speed to be not 1.0x
2. The timeline's listened/total/remaining timestamps change to respect the playback speed adjustment
3. Open the chapter list

Expected: Chapter timestamps are adjusted according to the speed adjustment
Actual: Chapter timestamps are not adjusted/scaled

### Audiobookshelf version

v2.2.17

### How are you running audiobookshelf?

Docker

**Comment by KF5JWC** [comment]
Thank you :)

**Comment by advplyr** [comment]
Updated in [v2.2.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.19)

**Comment by dedors** [comment]
This is still a issue with the history.

BUT, I would really like an option to disable the re-calculation of played & total time everywhere. I'm fine with re-calculated remaining time.
Because when I change the playback speed mid book, it gets really confusing where I am.
Btw, this is the way SABP is handling playback speed, so I'm probalby not the only one that likes it/is used to that way
