### ISSUE TITLE
[Enhancement]: Save new cover with different name than overwriting it.

### ISSUE THREAD

**Issue by Dr-Blank** [advplyr/audiobookshelf#1655]
### Describe the feature/enhancement

I have enabled store cover with progress. And sometimes the folder has a `cover.jpg` already present in it which gets overwritten when the books are quick matched. There is no record of previous covers and the data is lost permanently.

The proposal here is to keep multiple covers by saving the new cover as maybe `cover.1.jpg` or `cover (1).jpg`, although I do not prefer whitespaces in file names.

Subsequent matches would simply increment the numbers to keep a record. 

One caveat of this would be if someone keeps matching again and again and just keeps saving the same covers with different file names. One solution of this could be solved by hashing the file to see if it is one of the other covers.

**Comment by hobesman** [comment]
This and a few related scenarios were discussed in the comments here: https://github.com/advplyr/audiobookshelf/issues/1548

But neither of those started out at what you're requesting so I think it makes sense to have a separate request specifically for this aspect.

**Comment by advplyr** [comment]
Related to #1548 and #1204

Might be worth merging these

**Comment by Dr-Blank** [comment]
Yeah, merging all these issues would be great as it all boils down to some kind of **cover management system**. And this system would address the point in the three open issues:
1. Having the ability to keep multiple covers.
2. Having the ability to store multiple covers on users file system.
3. Having the ability to not overwrite any existing data.

Closing this issue as solving other two would inherently solve this one.

**Comment by iconoclasthero** [comment]
I have a FR somewhere about covers: my thought was the ability to specify the names.  
It is my strong preference to have more ability to manipulate the files that ABS expects to have in directories and what it saves files as; `cover.jpg` and `metadata.json` are **far** to generic.  my desired path for the cover that abs uses by default is
<author>/<title>/title -- Cover 01.jpg
<author>/<title>/title -- metadata.json

it is annoying as **** that I cannot make everything in MY folder start with the title of the book so that I can manipulate it on the CLI via autocomplete the way that I prefer.
