### ISSUE TITLE
[Bug]: Automatic Tagging of series with a comma in the title results in two series being assigned

### ISSUE THREAD

**Issue by TobiasDax** [advplyr/audiobookshelf#1775]
### Describe the issue

When i match a book through audible some books will be part of a Series with a comma in the name.
This happens a lot with `Warhammer 40,000` Books and requires a lot of manual work to recreate the correct series after automatic matching.

The issue is quite similar to #916 i guess, but i did not want to hijack that issue.

### Steps to reproduce the issue

1. Automatically match a Book (through audible) that is part of a series containing a comma. For example
`B09PVLZQGK` `The Emperor's Finest` by `Sandy Mitchell`
2. Save the automatic Match
3. Check that it will have created the series for the Book, This should look correct for the moment
4. ??? Not sure when exactly it happens but you can trigger it by re scanning the library
5. Series should now be split into two series `Ciaphas Cain: Warhammer 40` and `000 #7`

### Audiobookshelf version

v2.2.20

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
In v2.2.21 the server setting to use `.json` files for metadata instead of `.abs` was added. If you change to `.json` this will solve the issue.
For users using Abs before 2.2.21 it will have to be changed manually to json. For new users this is the default.

![image](https://github.com/advplyr/audiobookshelf/assets/67830747/1f249456-5c95-4fc2-9235-440da74be40d)
