### ISSUE TITLE
"Page Unresponsive" in Chrome

### ISSUE THREAD

**Issue by seanap** [advplyr/audiobookshelf#179]
Hello, fantastic project! I imported my whole library, but now navigating the web app is very slow and every time I change screens (ex going from Issues to Library) it will hang for a while, then Chrome will pop up the unresponsive message.  I can click "Wait" and eventually it does load.  Could my library be too large? Are there any optimizations in the works for large album/file count?

I'm not seeing any errors in the logs.  It did take 3ish hrs to import my library, but I went through and fixed a few issues and did a rescan and it's been going for ~5hrs now.

**Comment by advplyr** [comment]
Wow! You must have a huge collection. The problem is that the library page is loading all of the books when it should really only load the books in view. I've known this would eventually need to be addressed, it just wasn't priority yet.

When you navigate around the other pages (excluding library) are those loading smoothly?

**Comment by advplyr** [comment]
I released v1.6.19 to help with performance on large libraries. I will move the discussion on that to #183
