### ISSUE TITLE
[Bug] Hide chapters page for ebook only book items

### ISSUE THREAD

**Issue by ambarnes2** [advplyr/audiobookshelf#1795]
### Describe the feature/enhancement

When editing an Ebook, there is an option to edit chapters, but when doing a lookup, it uses the Audiobook chapter lookup not one designed for Ebooks. It would be nice if we would be able to lookup chapters for ebooks.

**Comment by advplyr** [comment]
Ah this is actually a bug. We should be hiding the chapter tool when there are no audio files.

Unless you know of an API we can lookup ebook chapters?

**Comment by darth3pio** [comment]
*if the book doesn't have chapters embedded

Converting my Kindle library brings across chapter titles with it.

**Comment by advplyr** [comment]
@darth3pio How are the chapters stored? Inside the ebook file? What is the ebook file format?

EBook chapters and audiobook chapters need to be separate. I don't think we will be building something that modifies ebook chapters since that would be changing the structure of the epub.

**Comment by darth3pio** [comment]
Using the DeDRM plugin for Calibre, converting from encrypted AZW3 to EPUB.

Editing the contents of the EPUB in Calibre shows pages are in HTML format with an id attribute inside the body tag.

Instead of a CSS file this id is referenced inside a toc.ncx file which seems to provide a matching chapter header.

**Comment by advplyr** [comment]
Fixed in [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21)
