### ISSUE TITLE
[Enhancement]: Show book duration on Match page

### ISSUE THREAD

**Issue by jeff47** [advplyr/audiobookshelf#1803]
### Describe the feature/enhancement

It would be helpful when matching books where the narrator or ASIN are unknown to see the runtime of the file on the match page. 

Then you could quickly pick the one that has the runtime as the most likely match. 

![IMG_8823](https://github.com/advplyr/audiobookshelf/assets/7215369/6f1caec5-61bc-495b-824b-e5653738f1ba)

**Comment by advplyr** [comment]
Where would you suggest the duration be listed?

**Comment by jeff47** [comment]
Something like this maybe?

<img width="802" alt="Screen Shot 2023-05-28 at 12 16 17 PM" src="https://github.com/advplyr/audiobookshelf/assets/7215369/e74e2b6a-15d2-44d5-8037-0ad79b12c04d">

**Comment by danseitz** [comment]
Adding to the comments here since I had a duplicate request.

Here’s what I think would be a great way of implementing this in a subtle way that minimally changes the interface:
<img width="635" alt="image" src="https://github.com/advplyr/audiobookshelf/assets/3443594/370f0cc8-e85a-4239-96e8-42469e43e1ab">

**Comment by advplyr** [comment]
Added in [v2.5.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.5.0)
