### ISSUE TITLE
[Bug]: Invalid Data error when scanning files with file names containing certain characters 

### ISSUE THREAD

**Issue by listy-bit** [advplyr/audiobookshelf#1882]
### Describe the issue

[MediaFileScanner] Invalid data found when processing input

Where filename includes the character “:” or “.”

### Steps to reproduce the issue

1. Add file with “:” or “.” in filename to library. 

### Audiobookshelf version

2.2.23

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you sure this is due to the character and not the audio file itself? When you remove that character from the filename on the same audio file it scans fine?
Generally `:` shouldn't be used in filenames even though it is technically supported in linux. I'm not sure how this would cause issues with Abs though.

**Comment by esmoyer** [comment]
I just experienced this as well. Couldn't figure out why ABS wouldn't see the Audiobook. Found this post and removed the ':' from the filename and title and ABS found and added it. When I went to use the "Match" feature to add in the meta data, it pulled in the ':' for the title again and when I clicked Save, ABS showed "Invalid Data" error instead of the cover. As soon as I removed the ':' from the book title, it came back and all was good. So it would appear ABS doesn't like ':' in the book title and filename.
