### ISSUE TITLE
[Feature request] A button to submit bugs/features directly from the web-app

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#204]
Could you put a button (while you are in beta) on the page for easy bug/feature reporting?

PS: Please correct me if I am posting stuff on the wrong repository. I am just a bit confused as to whether to put this in audiobook-server or -web.

**Comment by advplyr** [comment]
That is a good idea, I will look into this.
I probably shouldn't have named it `audiobookshelf-web` because it is a bit misleading. That is actually the website https://www.audiobookshelf.org/.

`advplyr/audiobookshelf` is the server & web app
`advplyr/audiobookshelf-app` is the mobile app (android and soon iOS)

**Comment by raviwarrier** [comment]
Thanks and noted. Shall I move (if possible) my requests to audiobookshelf or I can start posting new ones there.

**Comment by advplyr** [comment]
Since all bug/feature requests will remain in github this would require authenticating with github from inside the web app and using their API. I think most people would prefer less requests to external servers and this being a considerable effort to implement I don't think it would be worth it.
Maybe pick this up in the future if we think of another way.

**Comment by raviwarrier** [comment]
That's understandable. At least, a link in the menu that takes someone to Github (whether they want to continue by signing in is up to them) would make the task of bug notification one step smaller.
