### ISSUE TITLE
[Bug]: azw3 file not able to be read with abs

### ISSUE THREAD

**Issue by Elekam** [advplyr/audiobookshelf#2058]
### Describe the issue

I have a azw3 file of Alan Rickmans Biography that I can open normally with sumatraPDF. But when opening it with abs's reader, it shows a jumble of symbols. This also happens trying to use the mobile App (0.9.65 (22)).

I am using abs v.2.3.3. in a docker container. I tried using the still fresh install of Microsoft Edge instead of my customized Firefox but same problem. I have the container behind a reverse proxy but even accessing the instance by IP:Port nothing changes. I suspect this really might be an abs issue?

![image](https://github.com/advplyr/audiobookshelf/assets/43169119/fb9bdb92-5c1e-4ade-9130-0e099428a283)

### Steps to reproduce the issue

1. Get a azw3 file?
2. Try to open it using abs
3. See an incorrectly opened book

### Audiobookshelf version

v.2.3.3

### How are you running audiobookshelf?

Docker

**Comment by DDriggs00** [comment]
I feel like this should be a feature request to add azw3 support, rather than a bug report.

**Comment by Elekam** [comment]
I didn't actually know there was no support for azw3, the documentation isn't quite clear on what is supported/i.e. it can be overlooked because it is only briefly mentioned in a chapter about something different. 
But yes, azw3 support would be great. I do not know how feasible this is though.

**Comment by DDriggs00** [comment]
This is now a dupe.

**Comment by nichwall** [comment]
Azw3 is currently supported, but will likely be dropped (from discussion in Discord)

**Comment by Elekam** [comment]
@nichwall How is it supported? I updated my abs to 2.4.4, the newest version, but when trying to read any azw3 file it still is unreadable?

**Comment by nichwall** [comment]
It's supported in that the extension is recognized so you could download it/send to a device, but not sure on how good the integrated reader is (as you've noticed with the rendering issues).

I haven't ever actually read an azw3 file since I already convert everything to epub. The focus will be shifting to epub since it's better supported by various devices and Kindles now support epub (also don't have a Kindle so just what I've seen from articles and conversation).

**Comment by advplyr** [comment]
When ebooks were experimental I setup an ereader that handled mobi and azw3 but it was very very primitive.

After doing more research into these formats it would be a large effort to build a better ereader, which is not worth the effort because mobi is old and dead.

I'm not sure where amazon is going to go with azw3 yet now that they are moving to epubs. They may start wrapping epubs in azw3 instead of wrapping mobi in azw3 in which case we may be able to use the epub ereader for it.

For now though I wouldn't expect any movement on mobi or azw3. I didn't put it in the github readme for that reason but haven't fully removed it from the official docs since it's technically still supported.

The azw3 test file I have used does work btw.
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/804be905-b305-457e-b832-c76b466b986f)

**Comment by Elekam** [comment]
Okay, thank you for the detailed response :D
I'm all for standards so if it seems like epub will be the go to for everyone thats great to hear. Ig I will be converting all my azw3 files to epub then. Thanks a lot :)
