### ISSUE TITLE
[Enhancement]: Sleep Timer - Until end of Current Chapter (Web App)

### ISSUE THREAD

**Issue by 0mni** [advplyr/audiobookshelf#2059]
### Describe the feature/enhancement

Would love to have the ability to have the sleep timer until the end of the current chapter.

**Comment by nichwall** [comment]
This is already implemented, assuming your audiobook has chapter markers.
https://github.com/advplyr/audiobookshelf/discussions/2051#discussioncomment-6894674

**Comment by 0mni** [comment]
Hmm, I am using the web based version, and it does not show as available. Just checked in the app, and that feature does exist.

**Comment by nichwall** [comment]
Ah, so you're specifically meaning on the web client. That shouldn't be hard to add.

Do you mind updating the issue title so it's more clear?

**Comment by nigiriemoji** [comment]
+1 on this enhancement. Sleep timer to end of chapter would be great for PWA or web version of ABS

**Comment by nichwall** [comment]
The best way to show support for a feature request is by reacting with a "Thumbs up" to the initial message of the issue instead of just saying `+1` or `I also want this`. When looking for new features, issues are sorted by the number of thumbs up reactions, not the number of notifications that an issue generated.

https://www.audiobookshelf.org/faq#i-have-a-feature-request-how-should-i-bring-this-up

**Comment by ZLoth** [comment]
Another thumbs up added.

![chrome 2024-05-17 13-19-11](https://github.com/advplyr/audiobookshelf/assets/6700159/beece8ef-bf05-45a9-b5ab-c8ef52495b02)

https://github.com/advplyr/audiobookshelf/assets/6700159/aaa29ee2-75a4-498e-9155-9689c72fbfac

**Comment by ZLoth** [comment]
Thank you.
