### ISSUE TITLE
[Feature request] Ability to hide/swipe/remove toast messages

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#209]
1. These fill up the screen and so it would be nice if we could swipe/cross them away. 
![image](https://user-images.githubusercontent.com/42061703/143800094-04f209f0-689d-48eb-b736-87bdefb28950.png)

2. Move the toast to the bottom right/left corner (especially the persistent ones like 'scanning library')

**Comment by advplyr** [comment]
You should be able to click to dismiss all toasts.
This is definitely a bug though. There should only ever be 1 scan running for a library at a time. Are you seeing any error messages in the logs?

**Comment by raviwarrier** [comment]
I couldn't find an 'x' on the toasts (perhaps it was the same color as the bg or small or invisible, i can't say). will check the next time I scan my library.

**Comment by advplyr** [comment]
There is a bigger problem here which is why are there so many scans open? It would be helpful if you could see if there are any error logs.

**Comment by raviwarrier** [comment]
There were quite a few errors in the logs for ~/metadata/logs/daily but none for scans. I couldn't really make sense of it, but here it is, in case you need it for your investigation - https://pastebin.com/EsztUE8T

**Comment by MidnightSnowleopard** [comment]
My experience for those messages has been that the scan took up a large amount of system resources apparently to the point where the connection to the server was dropped.  This caused a re-connection but the previous scanning library message stays in place likely because the library is still scanning and never received notification that the connection broke or the scan finished.  Re-connecting again during the scan creates another notification of a library scan in progress thus leading to the increasing number of them without removal.

**Comment by advplyr** [comment]
Scanner performance issues are consolidated here #444 which was the reason for the socket disconnections.
Toasts can be cleared by clicking on them.
