### ISSUE TITLE
[Feature request] Modern audiobook style for covers

### ISSUE THREAD

**Issue by raviwarrier** [advplyr/audiobookshelf#210]
Since the only format of books that will be on this server are audiobooks, why not use the standard (square-shaped) cover art for the books?
This is, of course, low priority request and can be addressed once all the functional bugs/features are fixed/incorporated.
![image](https://user-images.githubusercontent.com/42061703/143800721-9fc32cff-aef8-489b-a9c8-c898b1d708c7.png)

**Comment by advplyr** [comment]
I'm open to this. The reason I chose regular book cover aspect ratio is because the only place to get consistent square audiobook covers was from audible and audible wasn't integrated until recently.
I would want to make sure a 1.6:1 book covers also look okay inside a square aspect ratio. There are a few places audiobookshelf can get 1.6:1 book covers but only audible for square covers, so that is a limitation to consider.

**Comment by raviwarrier** [comment]
Understood; but it does affect the aesthetics of the app greatly (in a not-so-nice way). Perhaps, give an option to the user to choose the dimensions (I'm just spit-balling here, but will let you choose the best option).

**Comment by davidszp** [comment]
Could make this an option maybe? I would also prefer 500x500 as I have these embedded in all my m4b's.

**Comment by advplyr** [comment]
Just released `v1.6.33` with a server setting to use square book covers. I think eventually this will be a setting for each library.

![image](https://user-images.githubusercontent.com/67830747/144529044-9164ef67-4490-4fc0-8d5d-830b7ce687bd.png)

![image](https://user-images.githubusercontent.com/67830747/144529617-f6ed142c-71af-4bc3-ae08-11d305d09f2b.png)

**Comment by raviwarrier** [comment]
Awesome. Will check it out.

**Comment by raviwarrier** [comment]
Oh, this looks much better. I haven't been able to listen to books for a while now because of work, but the next book I start, I'll start testing your android app. Cheers.
