### ISSUE TITLE
[Bug]: Series splitting into multiple on commas

### ISSUE THREAD

**Issue by keaganhilliard** [advplyr/audiobookshelf#2167]
### Describe the issue

On the most recent update, ABS is splitting book series into multiple parts, "Books, Swords, & Stealth" becomes "Books", "Swords", "& Stealth"... "Memory, Sorrow and Thorn" becomes "Memory", "Sorrow", "and Thorn". Any idea why that would happen? Having commas in a series title is fairly common apparently.

### Steps to reproduce the issue

1. Tag a book with a series like "Memory, Sorrow, and Thorn"
2. Scan it

### Audiobookshelf version

v2.4.4

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
This should be fixed in 2.4.4. Do have metadata stored in a `.abs` file?
https://github.com/advplyr/audiobookshelf/issues/2100

**Comment by keaganhilliard** [comment]
No I don't actually have the library configured to store metadata with the item... I did move my ABS instance to another server using the backup feature (the file layout was the same but the inodes were different). It rescanned all of the files and messed up a ton of metadata, in that process the series were split.

**Comment by advplyr** [comment]
In 2.4.4 I updated the scanner so that it will use the metadata file as the source of truth no matter if it is stored with your item or in the `/metadata/items/` folder. That is something I had wanted to do for a while and didn't think about this case since we've been on `.json` for a while now.
I recommend switching to `.json` now before fixing everything because the .abs will be replaced once something is changed.
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/c1addc83-3778-4604-89cf-676f4643792b)

**Comment by advplyr** [comment]
We should probably drop support for .abs and write a migration script that migrates everyone over. I'm just not sure how many people wrote their own scripts based around that .abs format.

**Comment by keaganhilliard** [comment]
Yeah I guess I just assumed the database was the source of truth. I will switch it over to json and fix things. Thanks

**Comment by hobesman** [comment]
> We should probably drop support for .abs and write a migration script that migrates everyone over. I'm just not sure how many people wrote their own scripts based around that .abs format.

I was one of those people but I've already switched to the json files.
