### ISSUE TITLE
Genre not updating on a rescan

### ISSUE THREAD

**Issue by sguilly123** [advplyr/audiobookshelf#2194]
### Steps to reproduce

1.upadate the id3 tag of an existing audiobook in the library.
2.in the browser edit the book and rescan.
3.if I then update another field, e.g. asin and rescan, this is picked up and the genre is also update.

### Expected behaviour
- the genre should be updated
- 
### Actual behaviour
- it doesn't update.
-
### Environment data

Audiobookshelf Version: 2.4.4

Windows Edge browser. Synology NAS /Docker

**Comment by advplyr** [comment]
I don't understand. Can you give steps to reproduce the issue?

**Comment by kthxhi** [comment]
I believe I'm having the same issue. I use Mp3Tag for my audiobook metadata, and it has fields for: 

- GENRE
- #Genre 1 (aka TMP_GENRE1)
- #Genre 2 (aka TMP_GENRE2)

I make use of all three fields. For example:

- GENRE: Fiction
- #Genre 1: Historical
- #Genre 2: Mystery

I was adding my audiobooks to Audiobookshelf using that format. Then I realized ABS was only using the GENRE tag, so I edited my tags according to your documentation:

- GENRE: Fiction//Historical//Mystery

The new genres (Historical, Mystery) are not being updated to Audiobookshelf. It only shows what originally imported (ie "GENRES Fiction") on the main page for the audiobook, and also in its Edit field.

I have clicked on Settings➞Libraries➞Audiobooks➞Kebab Menu➞Scan.
I have also tried clicking Edit➞Rescan on individual audiobook pages.

They still just show "Fiction"

Same with changes to the title shown (ALBUM field). The only way I can make this metadata update is by deleting the book from the Audiobookshelf file system, and then scanning my library again. This adds it back in correctly. Editing title and genre using ABS also works - but since it doesn't seem to sync backwards, it means more manual effort to make sure all the data matches both my local file and ABS correctly.

I'm using Windows/Docker/Chrome browser. Please lmk if you need further info! So far I love the app besides these issues.

**Comment by advplyr** [comment]
Ah okay. I'm working on a scanner refactor for the next release that will solve for this. It will include docs explaining the scan process and how it pulls in data.

**Comment by kthxhi** [comment]
> I'm working on a scanner refactor for the next release that will solve for this. It will include docs explaining the scan process and how it pulls in data.

That's great - thanks so much for the quick reply!

**Comment by advplyr** [comment]
As of v2.5.0 the scanner metadata precedence is configurable. By default the `metadata.json` files overrides anything else. You can configure this now in the "Scanner" tab when editing a library.

https://www.audiobookshelf.org/guides/book-scanner
