### ISSUE TITLE
[Enhancement]: Add multiple series (when they exist) during quick match.

### ISSUE THREAD

**Issue by tehguitarist** [advplyr/audiobookshelf#2201]
### Describe the feature/enhancement

Currently, I believe that the metadata scraping just chooses the first series when scraping Audible in particular. 

For those books that have multiple series (many Star Wars, and Terry Pratchett's Discworld novels are great examples), it would be great to have the quick match grab both series. For example Discworld #1, Rincewind #1 (Discworld being the master series, Rincewind being the story arc within it). 
Another example are the Legend of Driz'zt books by R.A Salvatore. The whole series is 40 odd books long, broken down into 3-4 book arcs.

Not important, as it can be done manually, just a QoL thing to speed up the process.

**Comment by advplyr** [comment]
This is already supported. To see what data is coming back from the quick match for a specific book you can open the Match tab and whatever is the first result is what would be used for the quick match.

Using The Colour of Magic as an example:
![image](https://github.com/advplyr/audiobookshelf/assets/67830747/4afe06c1-4a92-4e29-93e8-55dcab886439)

The issue is not that Abs doesn't support pulling multiple series. It is that the metadata provider is only sending back 1 series.
