### ISSUE TITLE
[Enhancement]: Podcast Playlist Without Hanging on to Downloaded Episodes

### ISSUE THREAD

**Issue by tomershvueli** [advplyr/audiobookshelf#2216]
### Describe the feature/enhancement

I'm a heavy user of the podcasts feature in Audiobookshelf - this is something I've looked for a long time so thanks for the hard work that went into this! 
I created a 'Favorites' playlist for episodes that I really enjoyed. But I noticed that if I delete the episode file it'll remove it from the playlist. Since podcasts are accessible via their RSS feeds, I'm wondering if there's a way to allow episodes to stay in a playlist whether the episode is actually downloaded or not. The playlist can keep track of the pod's RSS and which episode, and provide the user a button to download the specific episode at a later point. The way I'm describing it it's almost like a bookmark for a certain podcast episode. 
Let me know if this makes sense in the overall vision for Audiobookshelf. 
Thanks!

**Comment by nichwall** [comment]
Audiobookshelf is designed as a media server (expects the media to be present). Whenever files are removed, they are also removed from the database. This functionality may change in the future, but not sure right now.

If you're wanting to keep track of podcast episodes that you like but don't want to keep the files, a media tracker may be more appropriate for your use case (such as Jelu or RYOT).

**Comment by advplyr** [comment]
Abs is meant for playing and managing your local media. 

I've been on the fence about these types of feature requests for a while now because if we go in this direction the scope of the project would expand to include features of a traditional podcast app. Except far more complex than a traditional podcast app because Abs also serves local media allowing users to create their own RSS feeds.

If we go this route we need some form of caching and polling feeds (similar to https://github.com/advplyr/audiobookshelf/pull/2178 ). The data model would need to change to support storing non-local episodes alongside local ones and keep them in sync (attempted here https://github.com/advplyr/audiobookshelf/pull/1047). The UI/UX on mobile would be difficult because we also have local downloads to the device.

There are a few other issues related to Abs becoming a traditional podcast app. #960 #1516

This is outside the scope of the project right now, but I wanted to speak generally on this also since it is brought up every so often.

**Comment by tomershvueli** [comment]
Understood, I appreciate the detailed and thoughtful response. Looking at the point of view of strictly a 'local media manager and player' the current functionality makes sense as it is, and pivoting would definitely require a bit of a refactor. I'll see how I can use it currently to fit my needs, thanks again!
