### ISSUE TITLE
[Enhancement]: Read Cue File For Chapters

### ISSUE THREAD

**Issue by jrpetersjr** [advplyr/audiobookshelf#2327]
### Describe the feature/enhancement

Hi,

I have multiple (80+) books that have multiple mp3 files and I also have a cue file that is has chapters in terms of the files, but I haven't been able to find an application that will work with the cue files that I have. Having ABS read the cue files for the chapters would allow me to have ABS embed the metadata and encode an MP4 just like it does when each file is it's own chapter. 

This may seem a bit confusing, but I can provide some data to look at to understand if needed.

**Comment by advplyr** [comment]
This probably won't get supported because of the limitations that CUE files have. Explained here https://github.com/sandreas/m4b-tool/issues/103#issuecomment-731322965

A feature has been requested for exporting CUE files which is less likely to be supported https://github.com/advplyr/audiobookshelf/issues/909
