### ISSUE TITLE
Unfortunately, the entire application needs improvement.

### ISSUE THREAD

**Issue by p6002** [advplyr/audiobookshelf#2364]
### Describe the feature/enhancement

I tested audiobookshelf for a month, here are the problems I encountered:

- There is no point in downloading podcasts locally because the Internet is required for the application to work (really?).
- It is necessary to switch between servers manually. One local server for downloading files, another server for listening away from home (he can't download).
- No history of episodes listened to.
- Completed podcasts often appear as in progress.
- No automatic downloads, you have to manually check every day for new podcasts.

These few errors definitely eliminate the point of using this application as the main source of podcasts. It's a pity because the idea is interesting and I like the ability to add audiobooks.
I'm just going back to PocketCasts, and I can't even find what podcasts I listened to so that everything is correct...

**Comment by DieselTech** [comment]
A lot of your points are just wrong.

> There is no point in downloading podcasts locally because the Internet is required for the application to work (really?).

You'll need internet access to download the podcast, but you don't need internet access to listen to downloaded podcasts on the same network as ABS. On the mobile apps if there isn't internet access at the time it will default to locally downloaded media.

> It is necessary to switch between servers manually. One local server for downloading files, another server for listening away from home (he can't download).

That is solved at the moment by using split DNS (Having your local DNS server hand out the inside IP as a response while inside the network) or hairpin NAT.

> No history of episodes listened to.

The podcasts series page keeps track of what is listened to already. 

![image](https://github.com/advplyr/audiobookshelf/assets/30128380/f954993b-7116-476a-84e0-4f580db4b6e1)

> No automatic downloads, you have to manually check every day for new podcasts.

There is automatic downloads. You setup a schedule to check for new episodes in the series detail view:

![image](https://github.com/advplyr/audiobookshelf/assets/30128380/997e3f55-bbf2-4a32-88f9-6d2b2b95c4a6)


Honestly it sounds like you haven't even used the software with the complaints you have.

**Comment by p6002** [comment]
- I can't listen podcasts at work when my phone doesn't have internet access. I didn't mean listening locally at home without internet.
- I don't have a podcasts series tab, but if you mean latest tab, I have to manually click the green shield and then the episode disappears (no history). Additionally, in the same tab, when an episode is downloaded, the arrow icon is not green when completed, so I don't know what I downloaded when scrolling through this list every day.
- There is no option to automatically download podcasts to the mobile app. The server downloads them correctly, but I have to manually download them later in the application.

**Comment by hobesman** [comment]
I think part of the confusion is that this is posted under the server repository instead of the mobile app. Not a big problem but I think it caused confusion.

That being said, I think your first bullet point is still surprising because the mobile app is set up to be able to listen to locally downloaded content even when the device is offline.

As for a list of episodes listened to, for each podcast you can tap the funnel icon and change to display "completed" episodes and it will show which ones you've listened to. Perhaps a global history might also be nice. The home page does show the last 10 or so completed under "Listen Again"

The automatic downloads to the mobile app, and the split DNS/server address issues are both on the unwritten to-do list, and have been raised by others as well. Do you're not alone in that regard.

And the completed episodes showing as in progress is also a bit surprising. Where are you seeing that it's still in progress? On the home page? Or only when you open the episode details page? Or...?

**Comment by CLHatch** [comment]
What I read from this is he isn't so much making a bug report, but bitching about things he can't figure out how to do, and saying "I'm gonna use this other app since this one is crap".  This is very obvious since he can't seem to figure out how to do a bug report with the correct information (sounded like he meant listening at home to me also), or in the correct repo (this is the server repo, not the mobile app repo).

**Comment by hobesman** [comment]
Maybe so, but even complaining about what they couldn't figure out is a perfectly acceptable piece of feedback. If enough people complain that they can't find a feature, then maybe that's an indicator that they're unnecessarily hard to find. Maybe OP jumped to conclusions about what the app can and can't do, but I think maybe other people are jumping to conclusions as well around here.

Instead of publicly speculating about someone's intelligence and focusing on their perceived mistakes, try to politely correct them. Then if they insist on being confrontational instead of civil, then someone can moderate and block someone, or delete a post, or whatever. But being rude because you perceive someone else as rude is not going to make this a better place.
