### ISSUE TITLE
TITLE or ALBUM

### ISSUE THREAD

**Issue by kroko100** [advplyr/audiobookshelf#2374]
### Describe the issue

Hello !
The problem is the ID3 metadata in the audio files
For editing I use the Mp3Tag program
Until version 2.4.4, in the ID3 of the mp3 file, I entered the title of the book in the TITLE field, and in the ALBUM I entered the title of the series. Now it's the other way around: TITLE, you have to enter the series, and in ALBUM, you have to enter the title of the book.
And now I don't know, should I change the ID3 metadata in the audio files again?

### Steps to reproduce the issue

1. 

### Audiobookshelf version

2.6.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This is likely not the issue since series is not taken from either of those meta tags. The ID3 tags are listed here https://www.audiobookshelf.org/docs#book-audio-metadata

I'm not sure what is going on for you but you may have a look at the scanner guide https://www.audiobookshelf.org/guides/book-scanner

**Comment by advplyr** [comment]
I don't think I understand. The album ID3 tag can be used as the title as shown in the documentation
