### ISSUE TITLE
[Enhancement]: audiobookshelf as a universal podcast client

### ISSUE THREAD

**Issue by aaro-n** [advplyr/audiobookshelf#2375]
### Describe the feature/enhancement

Thanks to the audiobookshelf project, some podcasts cannot be played problems have been solved. I want to use audiobookshelf as a universal client, but I found some problems with audiobookshelf:
# Audio cannot be played online, it can only be played after downloading (WEB side).
All the general podcast clients I use can be played online. Audiobookshelf must be downloaded before it can be played, which will consume the traffic of deploying audiobookshelf. I deployed audiobookshelf on fly.io. The free package can cover my consumption. If I will When audiobookshelf is used as the main podcast client, these are not enough.
# Can the starred content in audiobookshelf be saved to an S3-like service?
The self-built service may be unstable. Although I can back up my own data, I still hope to save it to cloud storage.

**Comment by advplyr** [comment]
We've talked about this quite a bit and this is outside the scope of the project. Downloading podcast episodes from an RSS feed should be seen more as a quality of life feature to make getting episodes on your server easier instead of viewed as a traditional podcast app where you subscribe to RSS feeds.

I wrote some more thoughts on this here https://github.com/advplyr/audiobookshelf/issues/2216#issuecomment-1763423433

I'm not sure what you mean about the S3 service, feel free to expand on that and maybe I can help.
