### ISSUE TITLE
[Bug]: Cannot clear titles from the "Continue Reading Shelf"

### ISSUE THREAD

**Issue by oboe45** [advplyr/audiobookshelf#2449]
### Describe the issue

There are several titles shown in the Self "Continue Reading"
If I Select the option to remove an item from "continue reading", it stays, or it disappears but returns when I restart the app.
This is the same issue previously reported in V2.6.0 and reported as fixed in V.2.7.0

### Steps to reproduce the issue

1. Select the option to remove from continue reading
2. Observer immediate, or later results - items reappear

### Audiobookshelf version

V 2.7.0

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
Are you using the iOS app? Can you Remove Progress on one of the books and then mark the same book as Finished?

**Comment by oboe45** [comment]
I use both the web version and the ios APP.  Using the IOS App, This
workaround worked for the books that had been hanging around for weeks.

The workaround works, but a one step consistent process for the app and the
online version makes more sense - why would anyone normally take both
steps?

This is still a bug.

**Comment by nichwall** [comment]
This is a bug with the iOS app sometimes having duplicate progress percentages for a book and reporting both (one completed, one incomplete). The bug should be fixed, but leftover data in the app may not have been deleted if you encountered it without realizing.

How long have you been using the iOS app?

https://github.com/advplyr/audiobookshelf/issues/1983

**Comment by oboe45** [comment]
A couple of years - not sure .

As long as I am able to just clear the shelf of "Continues" in a reliable
fashion - its OK.

Are you saying that there is some inconsistency between the APP and the Web
version in the way they work for this item?  Do they not use the same DB?
If there is a difference, I would prefer to make the "continue Reading"
shelf optional - prefer not to see it at all than have it requiring some
kind of additional manual adjustments

The problem with a great app like this one is that minor issues become a
constant itch to keep scratching at even though there is really no point!

**Comment by nichwall** [comment]
No, the problem was a specific issue with the iOS app related to syncing and local playback (not really clear on all of the details since I don't have any Apple devices), with a few different ways the duplicate playback could come up. The extra sessions are not cleaned up automatically to ensure actual progress isn't accidentally deleted.

If you've been using the app for that long, it is most likely related to either a specific app version you were using that had the bug, or due to a migration issue that went unnoticed when you performed the server SQLite migration beginning in `2.3.x`.

It is recommended that you reset your mobile app if you haven't done this since the SQLite migration (only need to do it once since upgrading from `2.2.x`). There have been a few edge cases like this due to some checks against the old ID being forgotten (more information in the previously linked issue). In general you don't need to reset the app after server or app updates, but that specific migration caused a lot of headache.

There are already several feature requests for reordering, hiding, and making custom shelves between the server and app repo.

**Comment by oboe45** [comment]
What do you mean by "reset the app" - delete it and reload a fresh copy??

**Comment by advplyr** [comment]
If you had downloaded on the book with server `v2.2.24` or below there is a chance that the book created a duplicate record in the database. I mentioned that here https://github.com/advplyr/audiobookshelf/issues/1983#issuecomment-1783864608

It sounds like you did download the books a long time ago and could have hit that bug. If discarding the progress resolved it then it's fine.
