### ISSUE TITLE
[Feature request] Display % completion of ffmpeg concat or zip operations

### ISSUE THREAD

**Issue by GrapeApe230** [advplyr/audiobookshelf#250]
Is there anyway to display the status of the m4b concat or multi file zipping operation when choosing to download an audiobook? I think showing a % completion would be useful feedback.

**Comment by advplyr** [comment]
There is a way, but I think it would be a rough estimate. My initial thought is you would probe the output file every second or two and compare with expected values. I agree this would be nice, especially because m4b encodes can take a long time.

That entire download tab needs to be redone and re-thought out.
For example, I want to change the language to "convert", like Calibre. Then you could convert multiple mp3's to an m4b or vice versa.

**Comment by advplyr** [comment]
This implementation has changed now for the zip and for the m4b I don't think there is a reliable way to do this.
