### ISSUE TITLE
[Bug]: quick match overwrite all information in some situations

### ISSUE THREAD

**Issue by zombiehoffa** [advplyr/audiobookshelf#2517]
### Describe the issue

if I click on a book to edit then click "quick match"  sometimes it will overwrite all fields with a completely different book. I have noticed this happens when the first hit on audible is completely different than what the book actually is.

### Steps to reproduce the issue

1. click quick match while editing a book with a title and author
2. if audible has completely different info everything gets overwritten, I believe all the time but may just be sometimes. 

### Audiobookshelf version

v2.7.1 docker

### How are you running audiobookshelf?

Docker

**Comment by zombiehoffa** [comment]
try "Endangered Species" by "Gene Wolfe" as an example. First hit on audible is not that book and everything is overwritten by the first book result, including the already filled in  author and title.

**Comment by advplyr** [comment]
I believe this is because of #2400 where it was updated so that the audible search results are sorted by the one with the closest duration to match your book. Can you check if the result it is using has a closer duration then the correct one?

I can see how this would be problematic

**Comment by zombiehoffa** [comment]
Its the one that is on top for audible bools. It seemed more that the bool name was generic and furst hit wasnt the book. I will see what i can see when i get home but the bigg problem is it blows everything away rather than fillng unfilled stuff lile the tool tip says it will. If it just put in bad jnfo in the unfilled spots i could recover from that more easily

**Comment by advplyr** [comment]
Yes audible API doesn't always return exactly the matching book. Sometimes it appears to be random

**Comment by mikiher** [comment]
One more thing to check: Quick Match is only supposed to override existing details if "Prefer matched metadata" is enabled in the settings. Do you have "Prefer matched metadata" enabled? by default it's disabled. If you enabled it, consider disabling it.

**Comment by mikiher** [comment]
Also, I don't seem to find this specific book (Endangered Species by Gene Wolfe) on Audible. I tried to look it up on Google (sometimes it won't appear in Audible search results because of geo limitations, especially if you're outside the US) and could not find it too.

So it seems like this is not an issue of the Audible API not returning exactly the matching book - it just doesn't exist on Audible.

**Comment by mikiher** [comment]
@advplyr, Quick Match will always has the potential to do the wrong thing if the top search result is not the right one, and this will always happen for some books (if they don't exist on the provider, or if the title or author don't match, or for any other reason). Would you consider some sort of an "Undo Quick Match" button to help with such cases?

**Comment by zombiehoffa** [comment]
Thanks! I did have that set!

**Comment by advplyr** [comment]
Ah yeah thanks I didn't think to ask about prefer matched metadata.

There was a feature request to be able to preview quick match metadata before accepting. https://github.com/advplyr/audiobookshelf/issues/841

I'm not sure what would be better. It seems like having an "undo match" feature could be a better user experience because it wouldn't add an additional step. The additional step would only be for if you noticed it was wrong.

**Comment by advplyr** [comment]
I think the "prefer matched metadata" setting resolves this issue actually and we may not need to improve on the duration sorting from #2400 just yet. The given example just didn't have a match.
