### ISSUE TITLE
[Enhancement]: Increase native compatibility with the files migrated from Audible using Libation

### ISSUE THREAD

**Issue by DaTurkeyslayer** [advplyr/audiobookshelf#2539]
### Describe the feature/enhancement

Libation is an incredibly powerful tool for people migrating from Audible to their own hosting server solution. It automatically scans your Audible account and downloads all of your audiobooks, automatically linking them already with the different library sources. Not only can it do this one time, but it can also constantly be monitoring for new books being purchased, and then can download the file and put it directly into your ABS library folder.

It would be an absolute gamechanger for Audiobookshelf to incorporate the information Libation is able to grab from Audible such as "Last Heard, Bookmarks, Clips & Notes". Libation allows for this information of each of your audiobooks to be downloaded as either a CSV, Xlsx, or JSON, which if ABS (see screenshots) could intake and allow the end user to select for which ABS user the information would be applied too, this would allow for incredibly efficient and streamlined migration from Audible to ABS, for multiple users who might already be using Audible's library sharing functionality.

![image](https://github.com/advplyr/audiobookshelf/assets/44244497/23e2ca31-824d-4397-8abd-dca2a419d61f)
![image](https://github.com/advplyr/audiobookshelf/assets/44244497/581f3962-9a16-4389-97c8-1d322ce75c18)

Another quick note on this too... currently Libation applies the Genre tags to the file as a single string, instead of semicolon separators, so if ABS was able to clear those out before adding them to the library that would also streamline migration (as of now you have to manually remove all tags one by one and then re-match to the database to get them added correctly)

![image](https://github.com/advplyr/audiobookshelf/assets/44244497/1849616a-91be-4964-a3c6-8d31175174d5)
![image](https://github.com/advplyr/audiobookshelf/assets/44244497/cb890233-eab5-4dd4-9986-0bced0655dea)

Thank you so much for taking the time to look through this! Let me know if you have any questions but hopefully this makes sense! Thank you also for ABS as a whole, this is an absolutely amazing tool! Thank you!!!!

**Comment by nichwall** [comment]
This is probably outside the scope of ABS for similar reasons as this FR https://github.com/advplyr/audiobookshelf/issues/2112, but some of the parts could be implemented.

How would ABS be able to tell which account the files should be added to, since all books can be located in the same folder but could come from more than one user?

Really the only way I could see that working would be to have this only apply when using the upload feature (and not adding through the filesystem) since then the server knows which user is adding the book, which would then not be a consistent "adding books" process. It could also be done by requiring a library to have distinct folders by user, and linking a user to a folder, but that also feels like it would not be a good user experience and confusing documentation.

Another option would be to still ignore the extra notes and information during scan, and having an upload field that a user could use to import notes and bookmarks. (Related FR: https://github.com/advplyr/audiobookshelf/issues/2013, https://github.com/advplyr/audiobookshelf/issues/1890)

Tags and genres can include commas, so if there is not a unique separator, there isn't really a good way to automatically replace the tags. This could possibly be handled by this FR, but would need to be implemented differently with substring matching or something. https://github.com/advplyr/audiobookshelf/issues/1864

**Comment by advplyr** [comment]
I agree with @nichwall, I think this is outside the scope of the project. Abs has API endpoints to do everything like adding bookmarks so perhaps someone could write a script for that.

As for the genre tag I think you should open up a FR with libation and request changing how genres are embedded in audio files. As nichwall pointed out Audible for example uses commas in some of there genres which would break a comma separated list. I don't think we should add an additional setting just to skip importing genre meta tags. There is a setting in the library scanner settings to skip using audio file meta tags altogether.

**Comment by DaTurkeyslayer** [comment]
Thanks for the insight and response! Yeah this is all new to me!

I did just try turning the setting in the library scanner to skip using the
audio file meta tags, however that also then meant all the books lost there
chapters, so that doesn't work for this use-case.

Hmm, well yeah my primary point for making the request is that I do believe
the more streamlined the process of offboarding to audible and into ABS, in
general, the better. And right now that process even with Libation is kinda
clunky and you lose data, even though it is all there. But yeah I
understand such changes are technically out of scope, but if someone were
to tackle it I think there would be some sweeping benefits. :)

Again appreciate your time and everything that has been built out in ABS,
super thankful to be able to get this set up for my dad as he has been
frustrated by not having a central place for all of his audiobooks for a
good while now.

Thanks!

**Comment by nichwall** [comment]
Another thing you could do since you're already getting the books from Audible is to make sure the ASIN is in the directory structure to ensure the match is correct, and then can use the chapter lookup to pull the chapter data. I don't think the chapter lookup works for batch operations yet, and does not account for shifting timestamps (such as if you're trimming the Audible intro/outro). As it is right now that would be more clicks, but would help solve the genre issue.
