### ISSUE TITLE
[Enhancement]: Metadata Provider

### ISSUE THREAD

**Issue by GamerClassN7** [advplyr/audiobookshelf#2598]
### Describe the feature/enhancement

HI, 
would be possible to add metadata provider prom this source https://audioteka.com/

Most of books in my country are available there :)

Thank you in advance!

**Comment by nichwall** [comment]
Is there a public API that can be used? I'm not seeing anything on their website.

**Comment by advplyr** [comment]
If you know of an API we can use then we can re-open this

**Comment by GamerClassN7** [comment]
> If you know of an API we can use then we can re-open this

Hello sorry, for late response i missed the messages, there is not open API, how ever there is one for theirs android app. couldn't it be used ?

**Comment by GamerClassN7** [comment]
and i also found some python module 
https://pypi.org/project/audtekapi/

**Comment by nichwall** [comment]
With the addition of Custom Metadata Providers (under metadata tools in the server settings), you can make a custom API locally to convert the requests for ABS for other providers. Since it's not a publicly available API, it probably won't be part of the main codebase, since any changes to their API would require a new ABS version to be released (and gets more complicated as more providers are added).

The guide for this has not been written yet, but you can see what ABS will send and what ABS expects to get back in the following OpenAPI spec.
 https://github.com/advplyr/audiobookshelf/blob/master/custom-metadata-provider-specification.yaml

**Comment by nichwall** [comment]
Someone created a custom provider for Audioteka and added it to the docs if you are still looking for that. 

https://github.com/audiobookshelf/audiobookshelf-web/pull/108

**Comment by xypherose** [comment]
Hi, I've managed to find Audioteka API: https://api-audioteka.audioteka.com any chance for adding this to audiobookshelf?
