### ISSUE TITLE
[Bug]: Metadata not found when adding a new library

### ISSUE THREAD

**Issue by derhappy** [advplyr/audiobookshelf#2615]
### Describe the issue

We have a functioning library based on a single folder with all our audiobooks. For all audiobooks we maintained metadata and covers, stored at the central location.
Now I need to start separating the libraries, mostly between the kids and adults because there are some overlaps, but also many audiobooks which should only be visible to some of the users. 
I created a new library pointing to the same folder and started scanning. 
All audiobooks are found, but the metadata and covers are mostly missing. Some data seems to be downloaded, and embedded metadata is also found, but the metadata and covers from the central location seems to be ignored.

### Steps to reproduce the issue

1. Create library with centralized metadata and covers
2. Create new library pointing to the same data folder
3. Start scan to fill the library

### Audiobookshelf version

v2.7.2

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
So you are not using the "Store Metadata with Item" or "Store Cover with item"?

This is expected behavior because there is no overlap in library items between libraries in the database. The files that are getting the correct metadata are probably ones you embedded the metadata back in to the media put the metadata in the folder with the media, or just had correct metadata to begin with.

You will either need to store the metadata with the library items themselves or manually edit the database to move things around between libraries. You will also need to manually copy user progress to the new library items if you # care about that.

Another option is to limit user access by tags instead of library.
