### ISSUE TITLE
[Bug]: Author Match for Stephen Fry matched to Stephen Fried

### ISSUE THREAD

**Issue by andrewinmoco** [advplyr/audiobookshelf#2624]
### Describe the issue

When I clicked "Match All Authors"  under the Authors tab Steven Fry (who should be ASIN B000APAGVS) matched to   Steven Fried (ASIN B000AQU40K). 

### Steps to reproduce the issue

1. Have Steven Fry as an author
2. Click on authors tab
3. Click Match all Authors
4. View the author data and photo 

### Audiobookshelf version

v2.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Abs uses audnexus API to get author information and they get author information from audible.

I made an update that will use the exact match of author name from the search results returned from audnexus if an exact match is found.

I think Audnexus returns "Stephen Fried" as the closest match because in Audible "Stephen Fried" has a description and "Stephen Fry" does not. The search "Stephen Fry" weighs "Stephen Fried" higher because of the matches in the description.

I can see this being problematic with minor typos where it returns the exact match of an unknown author, but that is better than returning the wrong author on an exact match.

Stephen Fried has a description and image
https://www.audible.com/author/Stephen-Fried/B000AQU40K

Stephen Fry does not have a description or image
https://www.audible.com/author/Stephen-Fry/B000APAGVS

**Comment by advplyr** [comment]
Fixed in [v2.8.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.8.0)
