### ISSUE TITLE
[Bug]: v2.8.0 "MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process"

### ISSUE THREAD

**Issue by bendmunk95** [advplyr/audiobookshelf#2683]
### Describe the issue

Each time I try to scan an audiobook library, the socket disconnects about 5 seconds later and the scan does not occur. In the logs, I found this:

`Warning: connect.session() MemoryStore is not designed for a production environment, as it will leak memory, and will not scale past a single process.`

I'm running v2.8.0 in docker, no memory or CPU limits. I had watcher turned off, scanning libraries manually. Turning watcher on or off yields no different results. The issue seems to be if I have a directory labeled with `[Any Text Here]` is used. I'd love to be able to use brackets for tagging certain directories, but I understand this fix may be low priority.

### Steps to reproduce the issue

1. Attempt Library Scan with a audiobook directory beginning with `[Any text here]`

### Audiobookshelf version

v2.8.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
That warning is already reported here https://github.com/advplyr/audiobookshelf/issues/2538 and should not have anything to do with your issue.

The directory starting with `[Any Text Here]` should also not be your issue since this works fine.

Please check your crash logs in `/metadata/logs/crash_logs.txt`
