### ISSUE TITLE
Debian file system folder picker

### ISSUE THREAD

**Issue by szemlicka** [advplyr/audiobookshelf#269]
Hi,

I installed the version 1.6.45 via git on a debian system. I am not able to change the library. I am not able to select a folder. Its alwaqys empty and not select able.

Is there a trick?

**Comment by mx03** [comment]
Seems like the 1.6.45 can only select folders under the root of the app and the newest seems complete broken.

**Comment by advplyr** [comment]
Yeah this is actually why I started that FileSystemController @mx03. That method needs to check the OS and return as many paths as it can access, so on Windows it would ideally start with the drive letters.

The symlink solution should work for now. I'm not sure the best way to do this yet.

**Comment by szemlicka** [comment]
Hi, a link will not work for me. It looks like the app add the full path of the link to the original path.
install path /usr/share/audiobookshelf/audiobooks
Mount is /srv/audiobooks
App search for /usr/share/audiobookshelf/audiobooks/srv/audiobooks which doesn't exists.

**Comment by jpzbkk** [comment]
use sudo and edit the "fullPath" value in the data.0.json config, stored at:
/usr/share/audiobookshelf/config/libraries/data/data.0.json

then restart the service and refresh the library.

sym links didn't work for me, they kept adding the entire path instead of properly using the link.  also adding sym links into the automatically generated audiobooks folder half worked.  it recognzied books, but it added my root folder as the author.  so for now I would say editing the data.0.json file directly is the best bet.

I also copied data.0.json and made data.1.json in order to test and it created additional libraries, so its working good.

**Comment by advplyr** [comment]
Thanks, that's the only temp workaround for now.

For others using that workaround, be careful you don't make changes to the JSON files in an editor or IDE that is going to auto-correct syntax or add newlines.

**Comment by advplyr** [comment]
In [v2.0.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1) you can now manually enter in your folder paths.

Still no fancy folder picker for users of the debian package, but now you can have all the libraries and folders you need.
