### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by ostrokach** [advplyr/audiobookshelf#273]
It would be great if you could clarify the license under which the source code for audiobookshelf / audiobookshelf-app is released.

(Awesome project btw, thanks for making it!)

**Comment by advplyr** [comment]
Just added a license: https://github.com/advplyr/audiobookshelf/blob/master/LICENSE
Accidently put the wrong issue # in the commit... oops.

I was hesitant on this because I'm not a fan of verbose legalese, but it seemed the GNU GPL3 license made the most sense for this project.
Thanks for the heads up and support.
