### ISSUE TITLE
Enhancement: Sort audiobooks additional by series

### ISSUE THREAD

**Issue by mx03** [advplyr/audiobookshelf#274]
It would be great if there could be an option to sort audiobooks additional by series and order by volume.
If this option is active, sort by the wanted type, but keep audiobooks of one series together.

Alternative additional sort by:
no series: use title
series: use seriesname and volume number

**Comment by advplyr** [comment]
So adding "Series" to the sorting options, and have that sort the series alphabetical and the books in the series by volume?

**Comment by mx03** [comment]
Yes, but also with non series books displayed.

The best would be if it could be combined with every sorting.

**Comment by advplyr** [comment]
What would the UI look like?

**Comment by mx03** [comment]
Checkbox item inside the sort menu maybe

**Comment by MidnightSnowleopard** [comment]
Think this would be a general application of nested sorts.  Sort by series name as the primary sort key and then have secondary sorts based on different criteria like title or series number or the like.

I do like the idea and wanted something like this myself but except in the case of literally adding a check box somewhere on the UI for "sort by series name first" it seems like it may take a bit of work.

**Comment by mx03** [comment]
The easiest solution for a nested sort would be, custom pre defined sortings. User can create custom sorting in settings with a custom name and can then select this from the sort select

**Comment by advplyr** [comment]
I can see how a secondary sort can be useful in some cases. I'm not sure I see the value of sorting by series than volume number. What does this give you that the series page does not?

**Comment by MidnightSnowleopard** [comment]
The immediate use case I can think of is to be able to do something like sort by Author then sort by series, then by volume number.  Would give the ability to lay out multiple series from the same author in one view as well as the ability to see non-series books by an author in the same view as their series books.

**Comment by mx03** [comment]
Ok, if mean the library view. The view is useless for series if the series is not grouped together in the correct order.

Example: viewed Library with Author sorting, (filtered or unfiltered):
...
J. K. Rowling:
- Career of Evil (Cormoran Strike 3)
- Harry Potter and the Half-blood...(HP Series 6)
- Harry Potter and the chamber of sec... (HP Series 2)
- Harry Potter and the order of... (HP Series 5)
- Harry Potter and the philosop... (HP Series 1)
- Harry Potter and the the golbet of ... (HP Series 4)
- Harry Potter and the prisoner... (HP Series 3)
- Harry Potter and the deathly... (HP series 7)
- Lethal White (Cormoran Strike 4)
- The Christmas Pig (no series)
- The Cuckoo's Calling (Cormoran Strike 1)
- The Ickabog (no series)
- The Silkworm (Cormoran Strike 2)
- Troubled Blood (Cormoran Strike 5)

Next Author
- ...


Makes more sense: (sort by author AND (sort by title if not in series OR sort by seriesname AND volumenumber):
...
J. K. Rowling:
- The Cuckoo's Calling (Cormoran Strike 1)
- The Silkworm (Cormoran Strike 2)
- Career of Evil (Cormoran Strike 3)
- Lethal White (Cormoran Strike 4)
- Troubled Blood (Cormoran Strike 5)
- Harry Potter and the philosop... (HP Series 1)
- Harry Potter and the chamber of sec... (HP Series 2)
- Harry Potter and the prisoner... (HP Series 3)
- Harry Potter and the the golbet of ... (HP Series 4)
- Harry Potter and the order of... (HP Series 5)
- Harry Potter and the Half-blood...(HP Series 6)
- Harry Potter and the deathly... (HP series 7)
- The Christmas Pig (no series)
- The Ickabog (no series)

Next Author
- ...

**Comment by advplyr** [comment]
When sorting by author a secondary sort by series & sequence was added in [v2.0.2](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.2).
If this doesn't completely handle the use-case you mentioned we can re-open this.

**Comment by Travillion** [comment]
I am on v2.0.3 and this is not working consistently for me. I cannot figure out why.
I have my audiobook files (chaptered, single m4bs) meticulously tagged and so I have prefer metadata enabled in the scanner settings. I don't know if that makes a difference or not. When looking at the books, the subtitle field has the series and # (e.g., Jack Reacher, Book 18). Also, this information is the series field (e.g., Jack Reacher #18). I have checked that this is consistent for all the books in the series. Sometimes the books are sorted properly within a series, and sometimes they are not.

This is when sorting by Author. I think it would be nice if this also worked when sorting by Title. I understand that could get complicated because titles don't always include the series and so works within a series might not naturally be presented next to each other. Plex uses "title" and "sort title" fields, where sorting is based on the "sort title." In this way, individuals who want their library to keep series together when sorting by title can do so, by modifying the sort title. And those who don't like this can ignore the sort title field.
