### ISSUE TITLE
Can the piped audio out for audiobookshelf be linked to snapclient?

### ISSUE THREAD

**Issue by letshin** [advplyr/audiobookshelf#2779]
### Describe the feature/enhancement

Is it possible to add an option so that the audio output can be redirected to snapserver so it can be consumed by snapclients?

https://github.com/badaix/snapcast

**Comment by letshin** [comment]
I saw that ffmpeg is used and it is possible to pipe the ffmpeg output **(https://github.com/badaix/snapcast/blob/develop/doc/player_setup.md**:

ffmpeg -y -i http://wms-15.streamsrus.com:11630 -f u16le -acodec pcm_s16le -ac 2 -ar 48000 /tmp/snapfifo

and with docker it is possible to link the volumes together /tmp/snapfifo:/tmp/snapfifo so this should be possible?

**Comment by advplyr** [comment]
I'm sure it is possible but most of the audio files don't go through ffmpeg. Ffmpeg is only used in playing the audio when it has to be transcoded to an HLS stream because it can't be direct played.
This is outside the scope of the project for sure but there is an API you can use to build something out https://api.audiobookshelf.org
