### ISSUE TITLE
[Bug]: Title and X in corners of the web screen when editing the book

### ISSUE THREAD

**Issue by ZLoth** [advplyr/audiobookshelf#2985]
### What happened?

One thing that I noticed is that, when editing a book, the title of the book and the X are at the corners of the screen, and nowhere near the edit window. Shouldn't they be closer?

Chrome:
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/99e1593b-4b22-42ea-aa68-480b41f1727c)

Firefox:
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/56807c00-f55e-4a7d-a338-509f808280da)

Edge:
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/3ba2b0d3-73e7-452b-b2c6-d9b1c74315f9)

### What did you expect to happen?

As I'm editing the book, the title should be optional, but the X should be closer to the edit window. 

### Steps to reproduce the issue

Just edit a book and look at the corners of the browser window. 

### Audiobookshelf version

2.9.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

### Logs

```shell
No logs.
```

**Comment by advplyr** [comment]
Very early version of Abs put the close button in the top right of the modal. 

A user was having trouble closing the modal because they were looking in the top right of the screen for a close button. Even though clicking anywhere outside of the modal or pressing the escape key would close the modal, they were expecting the close button in the top right of the screen.

I thought it made sense to move it there because a) it frees up some screen space in the modal and b) it is not necessary to click that button to close the modal.

I'm not sure why this would be reported as a bug?

**Comment by ZLoth** [comment]
> I thought it made sense to move it there because a) it frees up some screen space in the modal and b) it is not necessary to click that button to close the modal.
> 
> I'm not sure why this would be reported as a bug?

It was unexpected, and I didn't notice it until a few days ago. Previously, I just clicked outside the box to close it without making changes, as I didn't notice a cancel button.
