### ISSUE TITLE
[Bug]: Re-scanning does not update file size

### ISSUE THREAD

**Issue by shaksternano** [advplyr/audiobookshelf#3144]
### What happened?

The file size displayed on the book summary does not change if the book files are updated. The correct file is displayed in the "Files" tab when editing a book.

### What did you expect to happen?

The file sizes of books in their summary should update after updating book files and then re-scanning the library. Re-scanning individual books does not work either.

### Steps to reproduce the issue

1. Upload a book.
2. Change the book files so that the total file size is different.
3. File size displayed in book summary does not change and remains the same as when the book was first uploaded.

### Audiobookshelf version

v2.11.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Firefox

**Comment by shaksternano** [comment]
Logs say the item was scanned and was up to date.

**Comment by ZLoth** [comment]
Testing here.... since I'm changing the files from MP3 to M4B....

Prior to the deletion:
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/9d662183-8ef8-4ed0-8084-a781026fe8bf)

After deleting the original MP3 files:
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/a6c1995d-6223-425f-8f3c-ebc5f60bcda8)

And, adding the new M4B files:
![image](https://github.com/advplyr/audiobookshelf/assets/6700159/1acb7237-49d6-48dd-a29e-0c94ed6ca7a8)

**Comment by shaksternano** [comment]
I should probably mention that for me I compressed the files in place, so the filename never changed. I also never deleted the files.

**Comment by advplyr** [comment]
I'm not able to reproduce this. Can you share exactly what you are doing to modify the file?
