### ISSUE TITLE
Edit series tag issue[Bug]: 

### ISSUE THREAD

**Issue by tdz262** [advplyr/audiobookshelf#3207]
### What happened?

If you enter "RI" in the series tag ABS freezes, The edit page isn't closeable and you can't select any of the series options. You need to refresh the Page before it works again. Copy and pasting the full name in works though. Typing it out it freezes once RI are entered. Tried this with multiple files.

### What did you expect to happen?

I have the series Ripple System. When entering the series information entering RI causing the window to freeze, I expected it to filter down the different series lists until the one i wanted was there.

### Steps to reproduce the issue

1. Try to edit a series tag and enter RI into the field.

### Audiobookshelf version

2.11.0

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Chrome

**Comment by nichwall** [comment]
Could you attach some browser logs when this happens (you can access these logs using F12)? Sounds like something on the page is crashing

**Comment by tdz262** [comment]
Ok i hit f12 when i came across the error. I copied the console page. What else am i suppose to do? 
[chromelog.log](https://github.com/user-attachments/files/16459618/chromelog.log)

**Comment by nichwall** [comment]
Thanks for sharing the log. And there isn't anything other indication in the UI that something broke? Like there are no error popups?

Looks like the same thing as https://github.com/advplyr/audiobookshelf/issues/2158 and https://github.com/advplyr/audiobookshelf/issues/2158, but a specific fix was not found.

If you're willing to share your database file (the SQLite file in `/config`, make sure your server is not running before copying the file) or a backup from `/metadata/backups`, that would be useful for reproducing the problem because a root cause hadn't been found. This can be emailed or DM'd on discord.

**Comment by nichwall** [comment]
After some research, it looks like this is due to duplicate series existing in the database, and duplicates of the same series being filtered cause the crash. Thanks to the database you provided, I found four different series of "The Wraith's Haunt Series " in the `series` table, as shown below.
![image](https://github.com/user-attachments/assets/dfd38e7d-806c-4aae-8d76-2a7efe2e96cd)

I was able to reproduce the issue of two characters causing the web client to get in an unresponsive state, such as:
- The Wr**ai**th's Haunt Series 
- The Wraith's Haunt Se**ri**es 
- The Wraith's H**au**nt Series 
- **Th**e Wraith's Haunt Series 
- The **Wr**aith's Haunt Series 

I added a debug print to the `itemsToShow` function in the InputDropdown component (original function shown below https://github.com/advplyr/audiobookshelf/blob/8774e6be718147759cf33412c896568f4eb892c2/client/components/ui/InputDropdown.vue#L74-L84).

![image](https://github.com/user-attachments/assets/5e4c547d-d74d-49a6-a7e1-065af84165ae)

### The Solution
I modified the `itemsToShow` function to only return unique entries, and that has fixed the web client crashing, and while this does fix the issue, this then leads to an issue of not knowing which of these series you are adding the book to.

A better solution is to ensure that duplicate series cannot be created, and add a database cleanup step (maybe during server startup?) to catch series with the same name that may exist from previous server versions. For example, right now if you go to the series view on your server, you will see 4 series with the same name, each with a single book in them.
