### ISSUE TITLE
Replay function

### ISSUE THREAD

**Issue by felixbro** [advplyr/audiobookshelf#329]
will there be some kind of replay function?
Like replay the hole book, audio-file, chapter, etc.? it would be nice to have it in the the browser and app too.

**Comment by advplyr** [comment]
I'm not sure what you mean. If you finish the book and press play again it will start at the beginning.

**Comment by mazmar** [comment]
I think he is referring to "repeat" function like on apple music or spotify, you can select to repeat whole album or repeat one song. or "shuffle"

repeat song will cause the same song to be continuously playing
repeat album will start the same album again after its done
shuffle will play in any order and not repeat


in audiobooks its possible to apply the same terminology:
repeat chapter -- will continuosly play the same chapter (instead of continueing to next one)
repeat book -- will start chapter 1 after last chapter
shuffle chapters -- will shuffle chapters

**Comment by advplyr** [comment]
That makes sense. Is this useful to many people? I particularly don't understand the shuffle chapters part.
I don't want to add features that hardly anyone will use because it clutters the interface.

**Comment by felixbro** [comment]
i meant repeat, not replay.
I and my children like to hear ambient sounds, which I would like to hear again and again and not want to restart them manually every time. I think an additional button would hardly be noticeable in the player.

![repeat_button](https://user-images.githubusercontent.com/64419976/151185550-68635f45-0d6d-4f66-8512-46aab3ef2fb9.jpg)

**Comment by advplyr** [comment]
When the ambient sounds are finished playing and you press play again, is it not restarting for you?
If you don't have any chapters then press the arrow left button should restart from the beginning
