### ISSUE TITLE
 [Enhancement]: missing translation 2.13+

### ISSUE THREAD

**Issue by Machou** [advplyr/audiobookshelf#3352]
Hello !

1. In French, we have a problem with new tranlsations here:

In French, we can say

Modifié le {date}

Items problems:

- Year of publication
- Date added
- Date of modification

Work with:

- Size
- Duration

![1](https://github.com/user-attachments/assets/5141d014-f9bd-4bd7-8839-995520722746)

-----

2. If the item is an eBook, Duration is useless ^^

![2](https://github.com/user-attachments/assets/a46bb1a4-446b-4497-8f3d-0f9d2d717c86)

-----

3. Upload a file: **Updated** & **Added**

![3](https://github.com/user-attachments/assets/fe75b9af-e701-47e6-8a35-de35762d5302)

-----

4. Upload a file, notification : **Successfully uploaded 1 item**

![4](https://github.com/user-attachments/assets/868e817a-795b-433b-a189-c8bb8fcd94f2)

**Comment by nichwall** [comment]
For point 1, you can edit the translation of `LabelFileModifiedDate` to put the `{0}` wherever the date should show up in the string.

**Comment by Machou** [comment]
> For point 1, you can edit the translation of `LabelFileModifiedDate` to put the `{0}` wherever the date should show up in the string.

Can i try my new tranlsation ? 

I use docker to try find my fr.json but i ddin't find it.

Maybe I did something wrong, here's how I did it:

```bash
docker exec -it audiobookshelf /bin/sh
find / -iname "fr.json"
```

If I can test my translations before publishing a release, that would be even better!

**Comment by nichwall** [comment]
I don't think you can edit the strings manually in the docker container, because the web client is built using those source files before the docker image is distributed. You can run from source with Node 20 installed on your system by cloning the project and then editing strings manually in `client/strings/fr.json`. The `npm run generate` command is what builds the web client (commands to build and run the server/client in the project readme).

https://github.com/advplyr/audiobookshelf?tab=readme-ov-file#manual-environment-setup

Edits to the language files should still be done through Weblate for the main project. If you can't run the server from source or in a development container, you can make changes on Weblate and then wait for the PR to be merged to see if everything looks correct in the `edge` docker image. This way is not great because you will have a long delay between when you make your edits and when the PR is merged to see your edits.

**Comment by Machou** [comment]
3. Upload a file: **Updated** & **Added**

![3](https://github.com/user-attachments/assets/fe75b9af-e701-47e6-8a35-de35762d5302)

**Comment by Machou** [comment]
4. Upload a file, notification : **Successfully uploaded 1 item**

![4](https://github.com/user-attachments/assets/868e817a-795b-433b-a189-c8bb8fcd94f2)
