### ISSUE TITLE
[Enhancement]: Not fetched bool

### ISSUE THREAD

**Issue by freitagdavid** [advplyr/audiobookshelf#349]
### Describe the feature/enhancement

Hate to keep requesting new features, but would it be possible to add some sort of To be Tagged or something along those lines boolean so that it would be possible to filter books that have been imported but not yet modified. I'm having some trouble going through everything and remembering what has been fetched and properly tagged and what hasn't.

**Comment by advplyr** [comment]
I'm not sure what you mean. It sounds like you may just need better batch tagging capabilities?

**Comment by freitagdavid** [comment]
Sorry for the late reply, no more just a marker that can be set on each book to let me know it hasn't been manually reviewed. I would expect this would be a more advanced user option so it could be hidden behind a setting or something along those lines. For example this is something I will do in my music applications where I'll have an import folder that gets automatically scanned I can use that piece of data for instance the folder being /toimport to then filter stuff that needs manual review before being moved. 

I'm talking about something similar but more built in, so basically just a bool to specify if a book has been manually reviewed whether that be through fetching the metadata, or editing. Though the more I talk about it the more complex it is sounding. Hrm, I know how I would implement it for myself though I'm not sure how that would work for a wider public.

**Comment by advplyr** [comment]
One of the first feature requests discussed in #13 was to add a "new" tag to every new audiobook. It had a flag that showed up when the tag "new" was on the audiobook. This didn't make it into production though.

![image](https://user-images.githubusercontent.com/67830747/153007308-5bd3db2c-6bd5-45d5-9dd0-dc4c75ab0a57.png)

If I'm understanding you correctly, a similar feature would solve your problem. If a tag was added automatically to each new audiobook that you had to manually remove after you reviewed it would that handle your use-case? You are right, this would need to be something you opt-in to in settings.

I'm not sure the flag graphic would be necessary because you can filter by tags now, but let me know what you think.

**Comment by freitagdavid** [comment]
Yes precisely what I was describing. I'm almost tempted to try and implement it myself. I've been itching to contribute to some open source code outside of my job as a lowly corporate dev. Gotta learn vue though.

**Comment by advplyr** [comment]
Go for it! You can learn as you go, no need to dig through docs.

**Comment by advplyr** [comment]
Filtering by unset metadata fields is in v2 and up. That should make this easier.
