### ISSUE TITLE
[Enhancement]: Enable IFRAME activation

### ISSUE THREAD

**Issue by miltuss** [advplyr/audiobookshelf#3684]
### Type of Enhancement

None

### Describe the Feature/Enhancement

Since update 2.17.3, IFRAME integration no longer works with ABS. And some Reverse-proxy like Caddy cannot activate ABS IFRAME. An ENV variable could give users the choice of whether or not to activate the IFRAME.

### Why would this be helpful?

I use ABS with the Organizr application which integrates other applications in IFRAME

### Future Implementation (Screenshot)

.

### Audiobookshelf Server Version

2.17.3

**Comment by advplyr** [comment]
Since this is a common request I made this a server setting.

![image](https://github.com/user-attachments/assets/9c37df1d-9529-4ab9-9a92-4c73633e777b)

Allowing iframe embed can also be enabled via an env variable `ALLOW_IFRAME` with a value of `1`.

Note: If it is enabled through the env variable there will be an error message shown when attempting to disable it in server settings. Env variable takes precedence.
