### ISSUE TITLE
[Enhancement]: Download via GUI?

### ISSUE THREAD

**Issue by mason-xx** [advplyr/audiobookshelf#390]
### Describe the feature/enhancement

First, just stumbled across your project and love it, exactly what i was searching for. Thanks a lot!

Quick question, how am I supposed to download a book? Love the m4b feature, but since the file is only generated on the filesystem or am I missing the option? Would be nice to have a link to the generated files via GUI.

**Comment by mason-xx** [comment]
Thanks for you reply, maybe a browser issue on my side. I don't get that link even if i stay on the page. The process works, but somehow it defeats the purpose if I would need to grab it from the filesystem directly.

Maybe a notification after completion with a link would do the job? Or maybe integrate it to the file page of the requested book? (Sorry im no coder and have no idea what is feasible?)

**Comment by advplyr** [comment]
It seems there is an error happening for you then because there is a notification when it is finished.

One way to make sure the m4b is generated correctly would be to open your file system and see if it is there and try to play it. Another way to check it is working is to watch the log fails and look for any errors or a log saying it was successful.

**Comment by advplyr** [comment]
Good news!
