### ISSUE TITLE
[Bug]: Deleted all my collection

### ISSUE THREAD

**Issue by kabaga** [advplyr/audiobookshelf#425]
### Describe the issue

I deployed the Docker container and pointed the "audiobooks" to where my collections are. The moment I brought it up. It deleted all my collection.

### Steps to reproduce the issue

1. Point the audiobooks to where the audiobooks are
2. run docker-compose up -d
3. check the audiobooks folder and they are all gone

### Audiobookshelf version

v1.7.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Abs deleted your audiobook files from your drive?

**Comment by kabaga** [comment]
Yes, ABS deleted everything. I have no idea why. I have mapped different non-empty folders to a docker container before. Don't know why it deletes my audiobooks. This is really frustrating. The NAS is a plain Debian 10.

**Comment by Stretox** [comment]
I deployed the current version on my truenas today and got the same problem

**Comment by Vito0912** [comment]
Please share your docker compose file. This very very likley is a configuration error

**Comment by Stretox** [comment]
I installed it as an application. My guess would then be that I gave it modify access to my library (Which I assumed was necessary to upload audio books through audiobookshelf 🤔)

**Comment by Vito0912** [comment]
I don't want to spam this old issue, but without proper configuration there is not much help possible, and the files are probably gone. 

You need to persistently map the volumes. 

If you don't do this, every time you update the container it will lose everything inside it. 
This is not related to ABS, but to Docker. 

I assume you uploaded everything through the web without proper mappings, so after an update you lost the temporary content. How you do proper mappings is more a question of your NAS and can better be answered either in their forums or in the ABS discord than in this old thread.
If you did not upload your books via the web interface, please add a new comment with saying so that you didn't.

**Comment by Stretox** [comment]
> I assume you uploaded everything through the web without proper mappings, so after an update you lost the temporary content. How you do proper mappings is more a question of your NAS and can better be answered either in their forums or in the ABS discord than in this old thread.

I think this was the issue. Luckily I had backups for my audiobooks so nothing is lost :)

Thank you again so much for helping me 🐳
