### ISSUE TITLE
Magazines support

### ISSUE THREAD

**Issue by binarygeek119** [advplyr/audiobookshelf#451]
### Describe the feature/enhancement

As the title says

**Comment by advplyr** [comment]
What is the file format for magazines? I've never had a digital magazine.
The experimental ebook reader supports ebook formats, comic formats and pdf.

**Comment by binarygeek119** [comment]
Pdf and comic book format but I was hoping for metadata with it

**Comment by advplyr** [comment]
What sort of metadata? Do you have any example apps that handle this? I'm not sure what to support here.

**Comment by genebean** [comment]
Would it be practical to separate magazines out into its own thing like books and podcasts are?

**Comment by advplyr** [comment]
It is unlikely this becomes its own media type and I don't know anything about magazine metadata.

If anyone has more specific details about magazines we can open this back up.

**Comment by loughnane** [comment]
What's needed for magazines are a "date" option somewhere. Either in the "series" field alongside the existing "sequence" option or as its own field on the same level as "publish year"

Anything simpler becomes a mess since some magazines are monthly, some ten per year, some weekly, some quarterly. Best to just go by publish date.

If I had that I could fill out the publisher, the 'series' would be the name of the publication itself, and then I'd have the date somewhere. All good.

**Comment by VIPKaiser** [comment]
This would be amazing! PDF format and the ability to select the cover page number as some magazines have the first page as an advert and the cover is the second page. I'd be happy to contribute to this.
