### ISSUE TITLE
[Enhancement]: Update Available Notification

### ISSUE THREAD

**Issue by Albuca** [advplyr/audiobookshelf#482]
### Describe the feature/enhancement

As referenced in https://github.com/advplyr/audiobookshelf/issues/480#issuecomment-1106817887, it would be nice if the application was able to notify the user if a new version is available.

Likely the easiest would be to compare the version referenced in package.json (https://github.com/advplyr/audiobookshelf/blob/d4525ad5ca3153b765bdbb730147a1c308eb2882/package.json) on github to that listed on the system. A link to the changelog would be a nice bonus.

This would cover version-to-version updates, but would not cover a re-release of an existing version. 

An option to turn off the 'update available' check in settings would also be nice, to cover those who do not want their software 'phoning home'.

**Comment by advplyr** [comment]
It's already set up to some extent https://github.com/advplyr/audiobookshelf/blob/master/client/plugins/version.js

The problem is I haven't put out the official release for v2 yet. The process of putting out releases and release notes/changelog is something we need to automate still. I'm going to be putting out the official v2 release now and anyone using 1.7.2 still will get the notification.

**Comment by advplyr** [comment]
![image](https://user-images.githubusercontent.com/67830747/164789517-f909c44d-476b-46b4-b032-547b164ba8f9.png)

Just pushed the v2.0.1 officially https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.1
