### ISSUE TITLE
[Bug]: Author Not Found

### ISSUE THREAD

**Issue by jflattery** [advplyr/audiobookshelf#572]
### Describe the issue

Unable to make a match for `Mark Russinovich`, `Mark E Russinovich`, or `Mark E. Russinovich`. (ASIN: B001IGNICC)

### Steps to reproduce the issue

1. Try to match author.
2. No match

### Audiobookshelf version

v2.0.11

### How are you running audiobookshelf?

Docker

**Comment by jflattery** [comment]
Perhaps there should be an additional method to match Author by ASIN

**Comment by advplyr** [comment]
Right now the levenshtein distance is set to 2 and the name `Mark Russinovich` is distance 3 from the name in audible `Mark E. Russinovich`. I think we should extend the levenshtein distance to 3 that would match the first name.

However, the other 2 names you listed should be matching since they are distance 1 and 0 respectively. When you are updating the author name are you pressing "Submit" before running the match again?

**Comment by jflattery** [comment]
Weird. So I just tried this again, I changed the name to `Mark Russinovich` hit `Submit` followed by `Quick Match` and no dice. Next I tried `Mark E Russinovich` hit `Submit` followed by `Quick Match` and this time it matched, but removed the `E` setting the name back to `Mark Russinovich` but now populating the image and ASIN.

**Comment by jflattery** [comment]
Multiple ASINs exist for "H. G. Wells":
[B08JKH6BRG](https://www.amazon.com/H.G.-Wells/e/B08JKH6BRG)
[B000AQ4FBE]https://www.amazon.com/H.-G.-Wells/e/B000AQ4FBE)
[B00V7F11YG]https://www.audible.com/author/H-G-Wells/B00V7F11YG)

**Comment by advplyr** [comment]
[v2.0.14](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.14) will use the ASIN value when quick matching if it is set.
