### ISSUE TITLE
[Enhancement]: Ability to set Podcast Episode Quantity and Age Limits

### ISSUE THREAD

**Issue by sydlexius** [advplyr/audiobookshelf#576]
### Describe the feature/enhancement

A feature in PocketCasts that I enjoy is to restrict certain podcasts (especially news-oriented ones) to a limited number of downloaded/queued episodes.  I can define this by quantity, maximum age, or both (as seen below).

![image](https://user-images.githubusercontent.com/1031594/167337501-a9a0c9eb-d278-4744-9a7f-bf9666c477ac.png)

**Comment by advplyr** [comment]
It will remove them from your file system after 2 days no matter whether you listened to it or not?

**Comment by jflattery** [comment]
@sydlexius, and to be clear, how would this feature implemented in your eyes? Would the episodes be archived on the server, the app, or both?

**Comment by sydlexius** [comment]
Having thought a bit more about this, this request is probably better
suited to the client-side. Should I resubmit my request?

**Comment by jflattery** [comment]
Yea perhaps close this and open it under `AudiobookShelf-App`

**Comment by sydlexius** [comment]
Resubmitting this request under `AudiobookShelf-App`

**Comment by advplyr** [comment]
It sounds like this is something that would need to be implemented on the server, web client and the app. I don't fully understand the feature though.

**Comment by jflattery** [comment]
My understanding is that the request is for the app to support archiving episodes downloaded to the device based on user defined criteria. So for instance, in Downcast, I can set a podcast to keep the last 3 episodes that haven't been marked as listened to. When an episode is completed, it is deleted from the phone. Is this what you are thinking @sydlexius ? Or do you want to also have the content removed from the server as well?

**Comment by feerlessleadr** [comment]
I originally thought that this would be a request for something like - only keep x amount of previous episodes, then delete. 

So if I have a daily news podcast that I have automatically download each day, but don't listen to for a week or 2, I probably don't want to listen to a daily news podcast that is a week or 2 old - hence having it auto-prune/auto-remove episodes older than a certain number of days. 

This would be a setting defined on a per podcast basis, since there are podcasts that would benefit from this, but obviously a lot of episodic podcasts that would not.
