### ISSUE TITLE
[Enhancement]: Use series name when collapsed

### ISSUE THREAD

**Issue by pints1ze** [advplyr/audiobookshelf#629]
### Describe the feature/enhancement

When using the collapse by series, can the list use the series name rather than the first book title?

**Comment by advplyr** [comment]
The collapse series option was something I wasn't sure about adding because it makes sorting and filtering unclear.
Currently it uses the first book in the series when sorting for every sort key.

For example:
If the first book title is "A" and the series is name is "B" then sorting by title will use "A".
It wouldn't make sense to use "B" because "B" is not a title, it is a series name. 

When sorting by "Added At" or "File Birthtime" it also only makes sense to use the first book in the series.

Filters add an additional level of complexity and confusion with collapsed series.

The inconsistency of it has had me considering taking it out altogether unless we can think of an elegant way to handle sorting/filtering. If we did show the series name instead of the first book title then we will get a bug report saying that it isn't in alphabetical order when sorting by title.

**Comment by nirurin** [comment]
I came here to ask the same thing, as for me personally being on the library view and seeing the first book of a series iis mostly meaningless, as I only know the series by the series name not "name of book 1" in many cases. 
I do see you reasoning that some people might prefer seeing the titles in alphabetical order... but they're still only seeing the title of book 1 in the right order, the rest of the books would be with it (in the wrong place lol). 

I can certainly see this being dependant on how people use the setup, so I just wanted to add my voice here to say - Maybe an option somewhere to turn on/off the ability to have stacked series named after the series, instead of the first book. 

I know you have the 'series' tab, which is great, but then you exclude all the books that aren't in a series if you're browsing.

**Comment by advplyr** [comment]
Yeah I hear you on that. I still don't think we have a good solution for the sorting issue this causes and using the first book at least makes sense when you sort. I'm just not sold on it yet, it feels hacky. I'm open to continue exploring ideas though.

BTW the initial thread that resulted in this feature is #322

**Comment by cassieesposito** [comment]
> If we did show the series name instead of the first book title then we will get a bug report saying that it isn't in alphabetical order when sorting by title.

We could make that a setting? Alternatively, if we were to replace the book title text with the series name text and the author of the first book with a list of all authors in the series, I bet it would be clear enough what's going on that the bug report might never come.

I'd be willing to code either/both of these solutions if I get the go ahead from you to pursue it, @advplyr

**Comment by advplyr** [comment]
I don't think we need a setting. What we would need to do is update the sorting functions on the server to check if collapse series is set and if so use the series name when sorting by title, otherwise put the collapsed series at the end.

**Comment by advplyr** [comment]
Added in [v2.0.24](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.24)

When sorting by title the series name will be used. When sorting by anything else the collapsed series will be at the bottom of the library.
