### ISSUE TITLE
[Bug]: Some MP3 Files will not be marked as "finished" after being fully played

### ISSUE THREAD

**Issue by Eftimin70** [advplyr/audiobookshelf#635]
### Describe the issue

Some MP3 Files will not be marked as "finished" after being fully played and the following status is displayed:

<img width="466" alt="Screenshot at May 27 17-10-09" src="https://user-images.githubusercontent.com/106393682/170728503-059af117-cf1b-4e9a-bbe6-1713ff0d12fc.png">

It would be nice if the checkmark "finished" would be set after playing an audiobook e.g. as soon as 100% is reached, instead of waiting for "0 sec remaining". 

### Steps to reproduce the issue

1. Happens with some MP3 files, typically the duration of these MP3 is longer than 20 minutes

### Audiobookshelf version

v2.0.17

### How are you running audiobookshelf?

Docker

**Comment by DieselTech** [comment]
Also experiencing this. 

![image](https://user-images.githubusercontent.com/30128380/170883048-d7ed5969-e42f-4f5d-969a-dc39e651cf3d.png)

**Comment by advplyr** [comment]
This should be fixed in [v2.0.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.18) since any progress update with less than 5 seconds remaining will mark it as finished. Another progress sync will get sent when the track actually ends.

When transcoding the duration is not always exact so marking it as complete when < 5 seconds remain should cover that.

**Comment by advplyr** [comment]
Fixed again in [v2.0.19](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.19)
