### ISSUE TITLE
[Enhancement]: Customize view settings per account

### ISSUE THREAD

**Issue by hobesman** [advplyr/audiobookshelf#638]
### Describe the feature/enhancement

I think it'd be nice if perhaps the admin sets the *default* display settings for all users, like wood vs alternate shelf view, and square vs non square covers, but then the admin has the option of allowing users to customize that for their account.

So basically four things: 
(1) a category of "default" display options, 
(2) an option whether to allow users to override the server defaults for their own account. This might be a universal toggle, or better yet a toggle on the permissions being granted each user, "Can customize 'View' settings for the account"
(3) an option by the user whether to override the server defaults (visible only if the account has that power) and
(4) a category of "my" display options, visible only if 2 and 3 are set to yes.

**Comment by advplyr** [comment]
In the mobile app this is configured on the device and doesn't come from the server settings. I could see moving the bookshelf view option to a user setting but I don't see it being valuable to disable the users ability to user since it wouldn't impact the mobile clients.

The square/non-square covers should be set per library depending on what covers you are putting on there. I don't think it would make sense to have that adjustable by the user.
