### ISSUE TITLE
[Bug]: Multi-file upload is putting multiple files under one book name instead of individual books

### ISSUE THREAD

**Issue by kymahi** [advplyr/audiobookshelf#670]
### Describe the issue

User is trying to upload their library to my server and using the bulk upload (issue is present both with adding individual files and a folder of files), and it is adding many files into folders of single books (e.g. random, unrelated book files are stored under /audiobooks/Robert Jordan/The Eye of the World/)

### Steps to reproduce the issue

1. have a large amount of books to upload
2. go to web uploader
3. start uploading all the books in bulk
4. observe the books are not separated, but stored under one or several books

### Audiobookshelf version

v2.0.18

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I see what you mean. Originally we required that each audiobook be placed in their own folder, so that is what the uploader is expecting.
This can be updated so that when you select multiple audio files or drag multiple audio files into the uploader they will be treated as separate books.
When you select a single folder that contains audio files or you drag and drop a single folder containing audio files this will still be treated as a single book.

**Comment by kymahi** [comment]
That makes sense. Thanks!

**Comment by advplyr** [comment]
This is added in [2.0.22](https://github.com/advplyr/audiobookshelf/releases/tag/v2.0.22)
Dragging or inputting only audio files into the upload form will treat each audio file as a separate audiobook. For podcasts they will all still be considered podcast episodes for the same podcast.
