### ISSUE TITLE
[Enhancement]: Batch Embed Metadata

### ISSUE THREAD

**Issue by burnshroom** [advplyr/audiobookshelf#700]
### Describe the feature/enhancement

Currently ABS does a great job of adding audiobooks via the watcher feature, which then I can simply go through each added book and match it to get the metadata up to date and it can be done fairly quickly.

However the embed metadate feature is a bit more involve. 

I propose an option to select a group of books and simply select an "embed metadata" option and allow ABS to handle the process in the background, as opposed to having to watch it embed each title individually and then manually move to the next file and do the process again.

**Comment by Demian98** [comment]
I would appreciate this feature very much. Currently, I'm using Postman to mass embed metadata by calling the REST API of ABS directly.

**Comment by advplyr** [comment]
Added in [v2.2.18](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.18)

Also included queueing so that only 1 audiobook will embed at a time

![image](https://user-images.githubusercontent.com/67830747/229633991-73b9b608-b8cf-4dc8-a336-5bcd88a99110.png)

![image](https://user-images.githubusercontent.com/67830747/229634058-cc98b646-466e-4dd5-9dff-f7211ecea736.png)

**Comment by benediktkr** [comment]
where in the UI is this? i running v2.2.18 but somehow havent managed to find it..

**Comment by advplyr** [comment]
You have to select items in the library or home page

**Comment by benediktkr** [comment]
aah, i found it now. 

<img width="284" alt="image" src="https://user-images.githubusercontent.com/174994/231781315-df3568de-19cd-4842-bfa9-d753bfd5eade.png">

i hadn't previous realized that they were selectable like that. thanks for the explanation :)
