### ISSUE TITLE
PRAISE! - No complaints or requests here, just praise.

### ISSUE THREAD

**Issue by Kudjo-Grand** [advplyr/audiobookshelf#71]
I've got nothing to ask for or point out or comment on here. 

I just wanted to take a moment to praise you for how awesome this has become! I'm impressed by your rate of progress and improvement. It has come from MVP to HIGHLY useable so fast! And in addition to that, you're adding super-handy features regularly.

Thank you! Thank you for making this, open sourcing it and "docker-izing" it so it can be easily self-hosted!!! I plan to use this for YEARS to come! It is absolutely PERFECT for what I was looking for.

Thank you again!

I wanted to make sure you heard some open, honest praise for your part in this excellent creation.

Keep it up, buddy!

**Comment by advplyr** [comment]
Thank you! I'm thrilled that you and others are finding value in this project.

I believe you are due for some praise as well. You have been continually thinking of ways to improve the software, testing new features, finding bugs, and providing feedback on updates. Without you and the few others contributing since beta, this project may have never made it out of pre-release.

So, right back at ya!
