### ISSUE TITLE
[Bug]: Error HTTP 413 at upload attempt

### ISSUE THREAD

**Issue by stemy2** [advplyr/audiobookshelf#825]
### Describe the issue

I can't upload anything. No matter the file i use, it results by a "error 413: Request entity too large".

### Steps to reproduce the issue

1. Create a library
2. Try to upload a file

### Audiobookshelf version

2.0.23~ynh1

### How are you running audiobookshelf?

Other

**Comment by Thovi98** [comment]
> 2.0.23~ynh1

It seems you are using Yunohost, right ? It's better to report the issues there because it's an Yunohost issue : https://github.com/Yunohost-Apps/audiobookshelf_ynh

You have to change the nginx config.

**Comment by Thovi98** [comment]
It’s already solved by https://github.com/YunoHost-Apps/audiobookshelf_ynh/pull/19 thanks to @ericgaspar.

**Comment by dit7ya** [comment]
Since this is a nginx setting thing actually, I am posting a link to the issue explanation here for the next person stumbling upon this 

[Nginx: 413 - Request Entity Too Large Error and Solution - nixCraft](https://www.cyberciti.biz/faq/linux-unix-bsd-nginx-413-request-entity-too-large/)

You essentially have to change `client_max_body_size` in your nginx config.

**Comment by ekasprzak** [comment]
How to change it when audiobookshelf is deployed using Docker?
Is nginx (and its conf) part of docker image?
