### ISSUE TITLE
[Enhancement]: Option to mark as played based on percentage listened 

### ISSUE THREAD

**Issue by Jdiesel87** [advplyr/audiobookshelf#837]
For me this has mainly been coming up with podcasts where the end credits can be quite long. It would be nice to have the ability to mark episodes as complete after a configurable amount of playback completion, say 90% or 95%.

I think it makes sense to limit it to podcasts as audiobooks are digested differently and are less likely to have end credits.

**Comment by advplyr** [comment]
Do you think this should be configurable per podcast or is this a library setting?

**Comment by Jdiesel87** [comment]
I think library setting should be sufficient. Personally I doubt I would spend the time to set it for each podcast. In my case I would probably set it at 5% and forget it.

**Comment by Catsrules** [comment]
Another vote for this feature! I know It is dumb but seeing a big list of book at that are 96-99% finished under my "Continue Listening" drives my OCD crazy. :) I end up just having to make sure I go to the very end on everything or mark it finished and delete the bookmark. 

As for how to implement it. I agree a global library setting should be fine. However percent remaining doesn't work very well when we are looking at very long duration content. For example 98% completed on a 2 hour book is only a few minutes that is totally reasonable. But 98% on a 30 hour book is 36 minutes. That to long to assume the book is finished. 

We might be better off just having a user defined minutes remaining instead of a percentage remaining.  For example If there is less than 5 minutes remaining assume it is finished. I think that works much better when you have content that has such a huge variation in duration. 

What are your thoughts?

**Comment by aether-coder** [comment]
Same problem, gotta go back and manually check as finished every once in a while since I leave when I start hearing the credits but that doesnt seem to be enough for it to be considered finished.

**Comment by advplyr** [comment]
@aether-coder When you mark an item as finished it isn't actually considered finished?

**Comment by aether-coder** [comment]
> @aether-coder When you mark an item as finished it isn't actually considered finished?

Yes, when I manually mark the audiobook as finish the progress bar goes from yellow to green, they are removed from continue listening and are moved to listen again section. This is great.

What I meant to say is that I almost always end up manually marking the audiobook as finished. Many audiobooks have credits or maybe even bonus content. For that reason there's always a minute, sometimes a few minutes left when I close the player and move on to the next audiobook. 

I get there are some pros and cons to impletementing a system that marks audiobooks (not to even mention podcasts) finished a few minutes earlier. In my opinion it would be best for everyone to have the option per library to consider audiobooks finished earlier. This could be percent based like 98%, and people can the percentage.

**Comment by lunik1** [comment]
This would be a nice to have for me too. I agree that absolute time remaining is a better metric than percentage remaining: a podcast's outro will be about the same length every time.

**Comment by advplyr** [comment]
Upcoming release library settings:
![image](https://github.com/user-attachments/assets/dfa05c79-f375-4ed7-90ff-22ceecf66b78)

**Comment by advplyr** [comment]
For downloaded media items in the mobile app the setting isn't respected for the offline copy of the media progress. The server will still show the item as finished but when in offline mode on the device the media item may still show as in progress.
I've opened an issue for this in the mobile app repo
https://github.com/advplyr/audiobookshelf-app/issues/1356
