### ISSUE TITLE
[Bug]: Audible search returns no results (522 status code)

### ISSUE THREAD

**Issue by dankeller** [advplyr/audiobookshelf#846]
### Describe the issue

Searching with title or ASIN returns no results.
Searching for author via magnifying glass or 'quick search' button returns no results.

Log entries:
[Audible] ASIN search error Error: Request failed with status code 522
[Audnexus] Author ASIN request failed for James%20S.%20A.%20Corey Error: Request failed with status code 522

Other sources work as expected.

### Steps to reproduce the issue

1. Search in Match tab using Audible.
2. Search for author using Quick Match button.

### Audiobookshelf version

v2.1.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
There is nothing we can do about this since the API is down.

**Comment by wtanksleyjr** [comment]
I just got this, and my question is: could ABS print an error message in addition to "no match" when it's one of these hard server errors? That way I can tell the difference  between "no match because of some kind of error" versus "no match even though no error happened." The latter means I probably typoed the author's name or something, while the former means I just need to wait.

**Comment by advplyr** [comment]
Yeah that makes sense
