### ISSUE TITLE
[Bug]: Genres including commas are sometimes treating the comma as a seperator

### ISSUE THREAD

**Issue by chyron8472** [advplyr/audiobookshelf#916]
### Describe the issue

![image](https://user-images.githubusercontent.com/12549803/185455641-41525fd7-a4ce-4b70-957f-815c519b7ff4.png)

I edited some of my books in ABS to assign them the genres "Fantasy, High" and "Fantasy, Low" so that they would be listed under "Fantasy" in the list of genres. However, sometimes I'm finding items having separate "Fantasy" and "High" genres instead.

### Steps to reproduce the issue

1. Tag a book with a genre that includes a comma
2. ???

### Audiobookshelf version

v2.1.2

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
This is a problem because of how the metadata.abs file is saving and parsing the genres.
The metadata.abs is storing genres as comma separated then when it gets re-scanned it will treat Fantasy and Low separately.

I guess it makes sense now why the genre ID3 tag uses `;` `/` and `//` as separators instead of commas.

**Comment by pkhanpara** [comment]
how do we fix this without breaking backward compatibility to read old metadata.abs?

**Comment by advplyr** [comment]
In [v2.2.21](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.21) I added an option to choose metadata.json instead of metadata.abs. For all new installs this will be the default, but for existing installs you will need to switch this over.
Once you switch over to JSON and press edit then save on a library item it will replace the metadata.abs with a metadata.json.

This will resolve these issues with commas.
