### ISSUE TITLE
Playback time is not being reported correctly

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#937]
### Describe the issue

Showing may longer for playing than it should.

![image](https://user-images.githubusercontent.com/101836977/186937976-3092f6dd-62eb-4e66-804e-6f9e91bdb0ad.png)

![image](https://user-images.githubusercontent.com/101836977/186938030-7d07f90f-5167-418b-9e27-5483cc38271d.png)

Probably related to me listening at 2.5x or more?

### Steps to reproduce the issue

1.  Play book
2. Check stats 

### Audiobookshelf version

2.1.4

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
The listening time should be independent from your listening speed. We have had a few updates related to listening time over the last coupon weeks so let me know if this persists recently on the latest updates.

I added that delete button to remove those listening sessions due to some of those bugs so you can clean up your stats if you want to.

We can re-open this if you have a recent example.
